;=======================================================================================
; Shared UI tile definitions and asset layout.
;
; Single source of truth for the UI tile/glyph set: chrome tile IDs, the
; bitmap-font enum, the 16 toolbar button IDs, asset sizing, attic load
; addresses, and the byte offset of every tile inside the loadable `uitiles`
; asset. Self-contained (no platform.asm deps).
;
; Shared by assets/ui_tiles.asm (lays the payload down at these offsets),
; assets.asm (loads the asset from disk and DMAs each tile into char RAM) and
; render.asm (draws the tiles). Pulled in once via main.asm for the main
; program, and directly by the standalone assets/ui_tiles.asm build.
;=======================================================================================

; --- Chrome tile IDs (1x1 FCM chars) ---
UI_TILE_PANEL           = 64
UI_TILE_MENU            = 65
UI_TILE_STATUS_LIGHT    = 66
UI_TILE_STATUS_DARK     = 67
UI_TILE_FRAME           = 68
UI_TILE_BOTTOM          = 69

; --- Bitmap-font glyph IDs (1x1), contiguous A..colon ---
UI_TEXT_A               = UI_TILE_BOTTOM + 1
UI_TEXT_B               = UI_TEXT_A + 1
UI_TEXT_C               = UI_TEXT_B + 1
UI_TEXT_D               = UI_TEXT_C + 1
UI_TEXT_E               = UI_TEXT_D + 1
UI_TEXT_F               = UI_TEXT_E + 1
UI_TEXT_G               = UI_TEXT_F + 1
UI_TEXT_H               = UI_TEXT_G + 1
UI_TEXT_I               = UI_TEXT_H + 1
UI_TEXT_J               = UI_TEXT_I + 1
UI_TEXT_K               = UI_TEXT_J + 1
UI_TEXT_L               = UI_TEXT_K + 1
UI_TEXT_M               = UI_TEXT_L + 1
UI_TEXT_N               = UI_TEXT_M + 1
UI_TEXT_O               = UI_TEXT_N + 1
UI_TEXT_P               = UI_TEXT_O + 1
UI_TEXT_Q               = UI_TEXT_P + 1
UI_TEXT_R               = UI_TEXT_Q + 1
UI_TEXT_S               = UI_TEXT_R + 1
UI_TEXT_T               = UI_TEXT_S + 1
UI_TEXT_U               = UI_TEXT_T + 1
UI_TEXT_V               = UI_TEXT_U + 1
UI_TEXT_W               = UI_TEXT_V + 1
UI_TEXT_X               = UI_TEXT_W + 1
UI_TEXT_Y               = UI_TEXT_X + 1
UI_TEXT_Z               = UI_TEXT_Y + 1
UI_TEXT_0               = UI_TEXT_Z + 1
UI_TEXT_1               = UI_TEXT_0 + 1
UI_TEXT_2               = UI_TEXT_1 + 1
UI_TEXT_3               = UI_TEXT_2 + 1
UI_TEXT_4               = UI_TEXT_3 + 1
UI_TEXT_5               = UI_TEXT_4 + 1
UI_TEXT_6               = UI_TEXT_5 + 1
UI_TEXT_7               = UI_TEXT_6 + 1
UI_TEXT_8               = UI_TEXT_7 + 1
UI_TEXT_9               = UI_TEXT_8 + 1
UI_TEXT_COMMA           = UI_TEXT_9 + 1
UI_TEXT_DOT             = UI_TEXT_COMMA + 1
UI_TEXT_DOLLAR          = UI_TEXT_DOT + 1
UI_TEXT_COLON           = UI_TEXT_DOLLAR + 1
UI_TEXT_COUNT           = (UI_TEXT_COLON - UI_TEXT_A) + 1

; --- Toolbar buttons (2x2, 4 chars each): one consecutive block of UI_BTN_COUNT.
; Slot order is defined by the ui_btn_* data blocks in assets/ui_tiles.asm
; (bulldozer, road, rail, ...). Slot i has char id UI_BTN_BASE + i*4. (Per-button
; name constants are intentionally omitted: 64tass is case-insensitive, so a
; UI_BTN_ROAD constant would collide with the ui_btn_road: label.)
UI_BTN_COUNT            = 16
UI_BTN_BASE             = UI_TEXT_COLON + 1

; --- Attic load address + asset sizing ---
ATTIC_UI_TILE_MB        = $80
ATTIC_UI_TILE_BANK      = $00
ATTIC_UI_TILE_ADDR      = $1000
UI_TILE_CHAR_SIZE       = 64
UI_TILE_INDEX_ENTRY_SIZE = 8
UI_BTN_CELLS_X          = 2
UI_BTN_CELLS_Y          = 2
UI_BTN_TILE_SIZE        = UI_BTN_CELLS_X * UI_BTN_CELLS_Y * UI_TILE_CHAR_SIZE
; 6 chrome + UI_TEXT_COUNT glyphs are 1x1; UI_BTN_COUNT buttons are 2x2.
UI_TILE_ASSET_COUNT     = 6 + UI_TEXT_COUNT + UI_BTN_COUNT
UI_TILE_INDEX_SIZE      = UI_TILE_ASSET_COUNT * UI_TILE_INDEX_ENTRY_SIZE
UI_TILE_PAYLOAD_SIZE    = ((6 + UI_TEXT_COUNT) * UI_TILE_CHAR_SIZE) + (UI_BTN_COUNT * UI_BTN_TILE_SIZE)
UI_TILE_ASSET_SIZE      = UI_TILE_INDEX_SIZE + UI_TILE_PAYLOAD_SIZE

; --- Payload byte offsets (producer <-> loader contract) ---
UI_ASSET_OFF_PANEL          = 0
UI_ASSET_OFF_MENU           = UI_ASSET_OFF_PANEL + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_STATUS_LIGHT   = UI_ASSET_OFF_MENU + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_STATUS_DARK    = UI_ASSET_OFF_STATUS_LIGHT + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_FRAME          = UI_ASSET_OFF_STATUS_DARK + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_BOTTOM         = UI_ASSET_OFF_FRAME + UI_TILE_CHAR_SIZE
; Glyph run, then the 16-button block; both generated by .for loops in the
; producer and loader, so the sequences live in exactly one place each.
UI_TEXT_OFF_BASE            = UI_ASSET_OFF_BOTTOM + UI_TILE_CHAR_SIZE
UI_BTN_OFF_BASE             = UI_TEXT_OFF_BASE + (UI_TEXT_COUNT * UI_TILE_CHAR_SIZE)
