;=======================================================================================
; UI/FCM tile and glyph data.
;
; Compiles standalone into the `uitiles` asset (loaded from disk at boot). The
; payload is laid out at the offsets in shared/ui_tile_layout.asm; tileloader.asm
; DMAs from those same offsets. The ui_glyph_* bitmaps MUST stay in
; UI_TEXT_A..UI_TEXT_COLON order, since the index/offsets are generated by loops.
;
; Record format:
;   .word tile id
;   .word payload size
;   .byte payload bytes
;=======================================================================================

        .cpu "45gs02"
        .include "../platform.asm"
        .include "../shared/ui_tile_layout.asm"

; Origin is irrelevant: position-independent data. It only sets the 2-byte PRG
; load-address header, which the boot loader strips (DMAs body from staging+2).
; $0000 so no reader infers a real address.
        * = $0000

ui_tiles_start:

; Text glyph border colour. Set to $0C (light grey, same as UI_TILE_PANEL
; and UI_TILE_MENU) so glyphs blend into the panel + chrome bar instead of
; punching cyan rectangles around each letter on the popup. Foreground is
; black -- baked in at asset-build time.
UI_TEXT_BG = $0C
UI_TEXT_FG = $00

UI_TEXT_ROW .macro p0, p1, p2, p3, p4
        .byte UI_TEXT_BG, \p0, \p1, \p2, \p3, \p4, UI_TEXT_BG, UI_TEXT_BG
.endmacro

; Commodore-style glyph macros. CBM_ROW takes one byte (8 bits, MSB first) and
; expands it into 8 palette indices (UI_TEXT_FG where the bit is 1, UI_TEXT_BG
; where 0). CBM_GLYPH stacks 8 rows of CBM_ROW into a full 8x8 FCM cell.
;
; The byte data matches the standard C64 character ROM bitmaps for uppercase
; A-Z, 0-9 and a handful of punctuation. Copy/paste from any C64 charset table
; (e.g. CHARGEN at $D000 in the C64 memory map).
CBM_ROW .macro b
        .byte (\b) & $80 ? UI_TEXT_FG : UI_TEXT_BG
        .byte (\b) & $40 ? UI_TEXT_FG : UI_TEXT_BG
        .byte (\b) & $20 ? UI_TEXT_FG : UI_TEXT_BG
        .byte (\b) & $10 ? UI_TEXT_FG : UI_TEXT_BG
        .byte (\b) & $08 ? UI_TEXT_FG : UI_TEXT_BG
        .byte (\b) & $04 ? UI_TEXT_FG : UI_TEXT_BG
        .byte (\b) & $02 ? UI_TEXT_FG : UI_TEXT_BG
        .byte (\b) & $01 ? UI_TEXT_FG : UI_TEXT_BG
.endmacro

CBM_GLYPH .macro b0, b1, b2, b3, b4, b5, b6, b7
        #CBM_ROW \b0
        #CBM_ROW \b1
        #CBM_ROW \b2
        #CBM_ROW \b3
        #CBM_ROW \b4
        #CBM_ROW \b5
        #CBM_ROW \b6
        #CBM_ROW \b7
.endmacro

UI_TILE_RECORD .macro index
.endmacro

#UI_TILE_RECORD UI_TILE_PANEL
ui_data_panel:
        .fill 64, $0C

#UI_TILE_RECORD UI_TILE_MENU
ui_data_menu:
        .fill 64, $0C       ; light grey -- matches UI_TILE_PANEL and UI_TEXT_BG

#UI_TILE_RECORD UI_TILE_STATUS_LIGHT
ui_data_status_light:
        .fill 64, $0C

#UI_TILE_RECORD UI_TILE_STATUS_DARK
ui_data_status_dark:
        .fill 64, $0C

#UI_TILE_RECORD UI_TILE_FRAME
ui_data_frame:
        .fill 64, $08

#UI_TILE_RECORD UI_TILE_BOTTOM
ui_data_bottom:
        .byte $08,$08,$08,$08,$08,$08,$08,$08
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $08,$08,$08,$08,$08,$08,$08,$08

#UI_TILE_RECORD UI_TEXT_A
ui_glyph_a:
        #CBM_GLYPH $18, $3C, $66, $7E, $66, $66, $66, $00

#UI_TILE_RECORD UI_TEXT_B
ui_glyph_b:
        #CBM_GLYPH $7C, $66, $66, $7C, $66, $66, $7C, $00

#UI_TILE_RECORD UI_TEXT_C
ui_glyph_c:
        #CBM_GLYPH $3C, $66, $60, $60, $60, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_D
ui_glyph_d:
        #CBM_GLYPH $78, $6C, $66, $66, $66, $6C, $78, $00

#UI_TILE_RECORD UI_TEXT_E
ui_glyph_e:
        #CBM_GLYPH $7E, $60, $60, $78, $60, $60, $7E, $00

#UI_TILE_RECORD UI_TEXT_F
ui_glyph_f:
        #CBM_GLYPH $7E, $60, $60, $78, $60, $60, $60, $00

#UI_TILE_RECORD UI_TEXT_G
ui_glyph_g:
        #CBM_GLYPH $3C, $66, $60, $6E, $66, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_H
ui_glyph_h:
        #CBM_GLYPH $66, $66, $66, $7E, $66, $66, $66, $00

#UI_TILE_RECORD UI_TEXT_I
ui_glyph_i:
        #CBM_GLYPH $3C, $18, $18, $18, $18, $18, $3C, $00

#UI_TILE_RECORD UI_TEXT_J
ui_glyph_j:
        #CBM_GLYPH $1E, $0C, $0C, $0C, $0C, $6C, $38, $00

#UI_TILE_RECORD UI_TEXT_K
ui_glyph_k:
        #CBM_GLYPH $66, $6C, $78, $70, $78, $6C, $66, $00

#UI_TILE_RECORD UI_TEXT_L
ui_glyph_l:
        #CBM_GLYPH $60, $60, $60, $60, $60, $60, $7E, $00

#UI_TILE_RECORD UI_TEXT_M
ui_glyph_m:
        #CBM_GLYPH $63, $77, $7F, $6B, $63, $63, $63, $00

#UI_TILE_RECORD UI_TEXT_N
ui_glyph_n:
        #CBM_GLYPH $66, $76, $7E, $7E, $6E, $66, $66, $00

#UI_TILE_RECORD UI_TEXT_O
ui_glyph_o:
        #CBM_GLYPH $3C, $66, $66, $66, $66, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_P
ui_glyph_p:
        #CBM_GLYPH $7C, $66, $66, $7C, $60, $60, $60, $00

#UI_TILE_RECORD UI_TEXT_Q
ui_glyph_q:
        #CBM_GLYPH $3C, $66, $66, $66, $66, $3C, $0E, $00

#UI_TILE_RECORD UI_TEXT_R
ui_glyph_r:
        #CBM_GLYPH $7C, $66, $66, $7C, $78, $6C, $66, $00

#UI_TILE_RECORD UI_TEXT_S
ui_glyph_s:
        #CBM_GLYPH $3C, $66, $60, $3C, $06, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_T
ui_glyph_t:
        #CBM_GLYPH $7E, $18, $18, $18, $18, $18, $18, $00

#UI_TILE_RECORD UI_TEXT_U
ui_glyph_u:
        #CBM_GLYPH $66, $66, $66, $66, $66, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_V
ui_glyph_v:
        #CBM_GLYPH $66, $66, $66, $66, $66, $3C, $18, $00

#UI_TILE_RECORD UI_TEXT_W
ui_glyph_w:
        #CBM_GLYPH $63, $63, $63, $6B, $7F, $77, $63, $00

#UI_TILE_RECORD UI_TEXT_X
ui_glyph_x:
        #CBM_GLYPH $66, $66, $3C, $18, $3C, $66, $66, $00

#UI_TILE_RECORD UI_TEXT_Y
ui_glyph_y:
        #CBM_GLYPH $66, $66, $66, $3C, $18, $18, $18, $00

#UI_TILE_RECORD UI_TEXT_Z
ui_glyph_z:
        #CBM_GLYPH $7E, $06, $0C, $18, $30, $60, $7E, $00

#UI_TILE_RECORD UI_TEXT_0
ui_glyph_0:
        #CBM_GLYPH $3C, $66, $6E, $7E, $76, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_1
ui_glyph_1:
        #CBM_GLYPH $18, $38, $18, $18, $18, $18, $7E, $00

#UI_TILE_RECORD UI_TEXT_2
ui_glyph_2:
        #CBM_GLYPH $3C, $66, $06, $0C, $30, $60, $7E, $00

#UI_TILE_RECORD UI_TEXT_3
ui_glyph_3:
        #CBM_GLYPH $3C, $66, $06, $1C, $06, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_4
ui_glyph_4:
        #CBM_GLYPH $06, $0E, $1E, $66, $7F, $06, $06, $00

#UI_TILE_RECORD UI_TEXT_5
ui_glyph_5:
        #CBM_GLYPH $7E, $60, $7C, $06, $06, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_6
ui_glyph_6:
        #CBM_GLYPH $3C, $66, $60, $7C, $66, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_7
ui_glyph_7:
        #CBM_GLYPH $7E, $66, $0C, $18, $18, $18, $18, $00

#UI_TILE_RECORD UI_TEXT_8
ui_glyph_8:
        #CBM_GLYPH $3C, $66, $66, $3C, $66, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_9
ui_glyph_9:
        #CBM_GLYPH $3C, $66, $66, $3E, $06, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_COMMA
ui_glyph_comma:
        #CBM_GLYPH $00, $00, $00, $00, $00, $18, $18, $30

#UI_TILE_RECORD UI_TEXT_DOT
ui_glyph_dot:
        #CBM_GLYPH $00, $00, $00, $00, $00, $00, $18, $18

#UI_TILE_RECORD UI_TEXT_DOLLAR
ui_glyph_dollar:
        #CBM_GLYPH $18, $3E, $60, $3C, $06, $7C, $18, $00

#UI_TILE_RECORD UI_TEXT_COLON
ui_glyph_colon:
        #CBM_GLYPH $00, $00, $18, $18, $00, $18, $18, $00

;=======================================================================================
; Toolbar buttons: 16 consecutive 2x2 tiles, each four 8x8 chars in tl, tr, bl,
; br order. One byte per pixel, low nibble = palette index. bulldozer and road
; have art; the rest reuse the placeholder box (#PLACEHOLDER_BOX) until drawn.
; Replace a #PLACEHOLDER_BOX line with explicit .byte rows to give that button a
; real icon. Order must match the UI_BTN_* enum in shared/ui_tile_layout.asm.
;=======================================================================================

; A 2x2 button box: $0B border, $05 interior.
PLACEHOLDER_BOX .macro
        .byte $0B,$0B,$0B,$0B,$0B,$0B,$0B,$0B   ; tl
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$0B,$0B,$0B,$0B,$0B,$0B,$0B   ; tr
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $0B,$05,$05,$05,$05,$05,$05,$05   ; bl
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$0B,$0B,$0B,$0B,$0B,$0B,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B   ; br
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $0B,$0B,$0B,$0B,$0B,$0B,$0B,$0B
.endmacro

ui_btn_bulldozer:

        .byte $0c,$0c,$0c,$0c,$0c,$0c,$0c,$0c
        .byte $0c,$0c,$0c,$0c,$0c,$0c,$0c,$0c
        .byte $0c,$1d,$1d,$1d,$1d,$1d,$1d,$1d
        .byte $0c,$0c,$0c,$1c,$0c,$0c,$0c,$1c
        .byte $0c,$0c,$0c,$1c,$0c,$0c,$0c,$1c
        .byte $0c,$0c,$0c,$1c,$1d,$0c,$0c,$1c
        .byte $0c,$0c,$0c,$1c,$1d,$0c,$0c,$0c
        .byte $0c,$0c,$1d,$1c,$1d,$1d,$1c,$1c
        .byte $0c,$0c,$0c,$0c,$0c,$0c,$0c,$0c
        .byte $0c,$0c,$0c,$0c,$0c,$0c,$0c,$0c
        .byte $1d,$1d,$0c,$0c,$0c,$0c,$0c,$0c
        .byte $0c,$0c,$0c,$0c,$0c,$0c,$0c,$0c
        .byte $0c,$0c,$1d,$0c,$0c,$0c,$0c,$0c
        .byte $1c,$0c,$1d,$0c,$0c,$0c,$0b,$0c
        .byte $1c,$1c,$1c,$1c,$0c,$0c,$0b,$0c
        .byte $1c,$1c,$1c,$1c,$1c,$0c,$0b,$0c
        .byte $0c,$1c,$1c,$1c,$1c,$1c,$1c,$1c
        .byte $0c,$1c,$1c,$1c,$1c,$1c,$1c,$1c
        .byte $0c,$0c,$1c,$0b,$04,$0b,$04,$0b
        .byte $0c,$0c,$04,$1c,$1c,$04,$04,$04
        .byte $0c,$0c,$0b,$1c,$1c,$04,$1c,$04
        .byte $0c,$0c,$0c,$04,$0b,$04,$0b,$04
        .byte $0c,$0c,$0c,$0c,$0c,$0c,$0c,$0c
        .byte $0c,$0c,$0c,$0c,$0c,$0c,$0c,$0c
        .byte $1c,$1c,$1c,$1c,$1c,$0c,$0b,$0c
        .byte $1c,$1c,$1c,$1c,$1c,$0b,$0b,$0c
        .byte $04,$0b,$04,$1c,$1c,$0b,$0b,$0c
        .byte $04,$04,$04,$0b,$0c,$0c,$0b,$0c
        .byte $1c,$1c,$04,$04,$0c,$0c,$0b,$04
        .byte $0b,$04,$0b,$0c,$0c,$0c,$0c,$0b
        .byte $0c,$0c,$0c,$0c,$0c,$0c,$0c,$0c
        .byte $0c,$0c,$0c,$0c,$0c,$0c,$0c,$0c

ui_btn_road:
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tl
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$00,$00,$00,$00,$00,$00,$00
        .byte $0C,$00,$00,$00,$00,$00,$00,$00
        .byte $0C,$00,$0F,$0F,$0F,$00,$00,$0F
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tr
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $00,$00,$00,$00,$00,$00,$00,$0C
        .byte $00,$00,$00,$00,$00,$00,$00,$00
        .byte $0F,$0F,$00,$00,$0F,$0F,$0F,$00
        .byte $0C,$00,$0F,$0F,$0F,$00,$00,$0F   ; bl
        .byte $0C,$00,$00,$00,$00,$00,$00,$00
        .byte $0C,$00,$00,$00,$00,$00,$00,$00
        .byte $0C,$0C,$00,$00,$00,$00,$00,$00
        .byte $0C,$0C,$00,$00,$00,$00,$00,$00
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0F,$0F,$00,$00,$0F,$0F,$0F,$00   ; br
        .byte $00,$00,$00,$00,$00,$00,$00,$00
        .byte $00,$00,$00,$00,$00,$00,$00,$00
        .byte $00,$00,$00,$00,$00,$00,$00,$00
        .byte $00,$00,$00,$00,$00,$00,$00,$00
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C

ui_btn_rail:
        ; Top-down railroad track running left-to-right: $05 ballast bed,
        ; $04 wooden cross-ties, two $0F steel rails (rows 5 and 10) spanning
        ; the full width, on the $0C panel background.
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tl
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $05,$04,$04,$05,$05,$04,$04,$05
        .byte $05,$04,$04,$05,$05,$04,$04,$05
        .byte $05,$04,$04,$05,$05,$04,$04,$05
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $05,$04,$04,$05,$05,$04,$04,$05
        .byte $05,$04,$04,$05,$05,$04,$04,$05
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tr
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $05,$04,$04,$05,$05,$04,$04,$05
        .byte $05,$04,$04,$05,$05,$04,$04,$05
        .byte $05,$04,$04,$05,$05,$04,$04,$05
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $05,$04,$04,$05,$05,$04,$04,$05
        .byte $05,$04,$04,$05,$05,$04,$04,$05
        .byte $05,$04,$04,$05,$05,$04,$04,$05   ; bl
        .byte $05,$04,$04,$05,$05,$04,$04,$05
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $05,$04,$04,$05,$05,$04,$04,$05
        .byte $05,$04,$04,$05,$05,$04,$04,$05
        .byte $05,$04,$04,$05,$05,$04,$04,$05
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $05,$04,$04,$05,$05,$04,$04,$05   ; br
        .byte $05,$04,$04,$05,$05,$04,$04,$05
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $05,$04,$04,$05,$05,$04,$04,$05
        .byte $05,$04,$04,$05,$05,$04,$04,$05
        .byte $05,$04,$04,$05,$05,$04,$04,$05
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C

ui_btn_power:
        ; Three utility poles on a couple rows of grass. Left pole tallest with
        ; two cross-arms, middle shorter with one, right shortest with none.
        ; $0C sky (panel background), $04 poles, $02 grass.
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tl
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$04,$0C,$0C,$0C,$0C
        .byte $0C,$04,$04,$04,$04,$04,$0C,$0C
        .byte $0C,$0C,$0C,$04,$0C,$0C,$0C,$0C
        .byte $0C,$04,$04,$04,$04,$04,$0C,$0C
        .byte $0C,$0C,$0C,$04,$0C,$0C,$04,$04
        .byte $0C,$0C,$0C,$04,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tr
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $04,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $04,$04,$04,$0C,$0C,$0C,$0C,$0C
        .byte $04,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$04,$0C,$0C,$0C,$0C   ; bl
        .byte $0C,$0C,$0C,$04,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$04,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$04,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$04,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$04,$0C,$0C,$0C,$0C
        .byte $02,$02,$02,$04,$02,$02,$02,$02
        .byte $02,$02,$02,$04,$02,$02,$02,$02
        .byte $04,$0C,$0C,$0C,$04,$0C,$0C,$0C   ; br
        .byte $04,$0C,$0C,$0C,$04,$0C,$0C,$0C
        .byte $04,$0C,$0C,$0C,$04,$0C,$0C,$0C
        .byte $04,$0C,$0C,$0C,$04,$0C,$0C,$0C
        .byte $04,$0C,$0C,$0C,$04,$0C,$0C,$0C
        .byte $04,$0C,$0C,$0C,$04,$0C,$0C,$0C
        .byte $04,$02,$02,$02,$04,$02,$02,$02
        .byte $04,$02,$02,$02,$04,$02,$02,$02

ui_btn_park:
        ; A tree (dark-green $03 outline, bright $07 foliage, $04 trunk) with a
        ; park bench ($04) beside it, on a couple rows of $02 grass. $0C sky.
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tl
        .byte $0C,$0C,$0C,$03,$03,$03,$0C,$0C
        .byte $0C,$0C,$03,$07,$07,$07,$03,$0C
        .byte $0C,$03,$07,$07,$07,$07,$07,$03
        .byte $0C,$03,$07,$07,$07,$07,$07,$03
        .byte $0C,$0C,$03,$07,$07,$07,$03,$0C
        .byte $0C,$0C,$0C,$03,$03,$03,$0C,$0C
        .byte $0C,$0C,$0C,$04,$04,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tr
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$04,$04,$0C,$0C,$0C   ; bl
        .byte $0C,$0C,$0C,$04,$04,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$04,$04,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$04,$04,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$04,$04,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$04,$04,$0C,$0C,$0C
        .byte $02,$02,$02,$02,$02,$02,$02,$02
        .byte $02,$02,$02,$02,$02,$02,$02,$02
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; br
        .byte $0C,$0C,$04,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$04,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$04,$04,$04,$04,$04,$0C
        .byte $0C,$0C,$04,$0C,$0C,$0C,$04,$0C
        .byte $0C,$0C,$04,$0C,$0C,$0C,$04,$0C
        .byte $02,$02,$02,$02,$02,$02,$02,$02
        .byte $02,$02,$02,$02,$02,$02,$02,$02

ui_btn_residential:
        ; House with a red roof, white walls and blue windows, an "R" in the
        ; top-right, on a couple rows of grass. $0C sky, $0D roof, $0F walls,
        ; $08 windows, $00 letter, $02 grass.
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tl
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0D
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0D,$0D
        .byte $0C,$0C,$0C,$0C,$0C,$0D,$0D,$0D
        .byte $0C,$0C,$0C,$0C,$0D,$0D,$0D,$0D
        .byte $0C,$0C,$0C,$0D,$0D,$0D,$0D,$0D
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tr
        .byte $0C,$0C,$0C,$0C,$00,$00,$00,$0C
        .byte $0C,$0C,$0C,$0C,$00,$0C,$0C,$00
        .byte $0C,$0C,$0C,$0C,$00,$00,$00,$0C
        .byte $0D,$0C,$0C,$0C,$00,$0C,$00,$0C
        .byte $0D,$0D,$0C,$0C,$00,$0C,$0C,$00
        .byte $0D,$0D,$0D,$0C,$0C,$0C,$0C,$0C
        .byte $0D,$0D,$0D,$0D,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0F,$0F,$0F,$0F   ; bl
        .byte $0C,$0C,$0C,$0C,$0F,$08,$08,$0F
        .byte $0C,$0C,$0C,$0C,$0F,$08,$08,$0F
        .byte $0C,$0C,$0C,$0C,$0F,$0F,$0F,$0F
        .byte $0C,$0C,$0C,$0C,$0F,$08,$08,$0F
        .byte $0C,$0C,$0C,$0C,$0F,$08,$08,$0F
        .byte $02,$02,$02,$02,$02,$02,$02,$02
        .byte $02,$02,$02,$02,$02,$02,$02,$02
        .byte $0F,$0F,$0F,$0C,$0C,$0C,$0C,$0C   ; br
        .byte $08,$08,$0F,$0C,$0C,$0C,$0C,$0C
        .byte $08,$08,$0F,$0C,$0C,$0C,$0C,$0C
        .byte $0F,$0F,$0F,$0C,$0C,$0C,$0C,$0C
        .byte $08,$08,$0F,$0C,$0C,$0C,$0C,$0C
        .byte $08,$08,$0F,$0C,$0C,$0C,$0C,$0C
        .byte $02,$02,$02,$02,$02,$02,$02,$02
        .byte $02,$02,$02,$02,$02,$02,$02,$02

ui_btn_commercial:
        ; Two blue office buildings (taller left, shorter right) with white
        ; windows and a "C" in the top-right. $0C sky, $08 buildings, $0F
        ; windows, $00 letter.
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tl
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$08,$08,$08,$08,$08,$08,$08
        .byte $0C,$08,$08,$08,$08,$08,$08,$08
        .byte $0C,$08,$0F,$08,$0F,$08,$0F,$08
        .byte $0C,$08,$08,$08,$08,$08,$08,$08
        .byte $0C,$08,$0F,$08,$0F,$08,$0F,$08
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tr
        .byte $0C,$0C,$0C,$0C,$0C,$00,$00,$00
        .byte $0C,$0C,$0C,$0C,$00,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$00,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$00,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$00,$00,$00
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$08,$08,$08,$08,$08,$08,$08   ; bl
        .byte $0C,$08,$0F,$08,$0F,$08,$0F,$08
        .byte $0C,$08,$08,$08,$08,$08,$08,$08
        .byte $0C,$08,$0F,$08,$0F,$08,$0F,$08
        .byte $0C,$08,$08,$08,$08,$08,$08,$08
        .byte $0C,$08,$0F,$08,$0F,$08,$0F,$08
        .byte $0C,$08,$08,$08,$08,$08,$08,$08
        .byte $0C,$08,$08,$08,$08,$08,$08,$08
        .byte $0C,$08,$08,$08,$08,$08,$0C,$0C   ; br
        .byte $0C,$08,$08,$08,$08,$08,$0C,$0C
        .byte $0C,$08,$0F,$08,$0F,$08,$0C,$0C
        .byte $0C,$08,$08,$08,$08,$08,$0C,$0C
        .byte $0C,$08,$0F,$08,$0F,$08,$0C,$0C
        .byte $0C,$08,$08,$08,$08,$08,$0C,$0C
        .byte $0C,$08,$0F,$08,$0F,$08,$0C,$0C
        .byte $0C,$08,$08,$08,$08,$08,$0C,$0C

ui_btn_industrial:
        ; Factory: dark-blue building ($01) with a red band ($0D) and lit yellow
        ; windows ($0A), a brown smokestack ($04) puffing gray smoke ($0B), and
        ; an "I" ($00) in the top-right. $0C sky.
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tl
        .byte $0C,$0C,$0C,$0C,$0B,$0B,$0C,$0C
        .byte $0C,$0C,$0C,$0B,$0B,$0B,$0C,$0C
        .byte $0C,$0C,$0C,$0B,$0B,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$04,$04,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$04,$04,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$04,$04,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$04,$04,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tr
        .byte $0C,$0C,$0C,$0C,$00,$00,$00,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$00,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$00,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$00,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$00,$00,$00,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$04,$04,$0C,$0C,$0C   ; bl
        .byte $0C,$01,$01,$04,$04,$01,$01,$01
        .byte $0C,$0D,$0D,$0D,$0D,$0D,$0D,$0D
        .byte $0C,$01,$01,$01,$01,$01,$01,$01
        .byte $0C,$01,$0A,$0A,$01,$0A,$0A,$01
        .byte $0C,$01,$0A,$0A,$01,$0A,$0A,$01
        .byte $0C,$01,$01,$01,$01,$01,$01,$01
        .byte $0C,$01,$01,$01,$01,$01,$01,$01
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; br
        .byte $01,$01,$01,$01,$01,$01,$0C,$0C
        .byte $0D,$0D,$0D,$0D,$0D,$0D,$0C,$0C
        .byte $01,$01,$01,$01,$01,$01,$0C,$0C
        .byte $0A,$0A,$01,$0A,$0A,$01,$0C,$0C
        .byte $0A,$0A,$01,$0A,$0A,$01,$0C,$0C
        .byte $01,$01,$01,$01,$01,$01,$0C,$0C
        .byte $01,$01,$01,$01,$01,$01,$0C,$0C

ui_btn_police:
        ; Sheriff/police badge: gold 5-pointed star ($0A) with black "PD" ($00)
        ; and a black shadow along the right edge for a 3D effect. $0C bg.
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0A   ; tl
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0A
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0A,$0A
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0A,$0A
        .byte $0C,$0C,$0C,$0C,$0C,$0A,$0A,$0A
        .byte $0C,$0C,$0A,$0A,$0A,$0A,$0A,$0A
        .byte $0A,$0A,$0A,$0A,$0A,$0A,$0A,$0A
        .byte $0C,$0A,$0A,$0A,$00,$00,$00,$0A
        .byte $0A,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tr
        .byte $0A,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0A,$0A,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0A,$0A,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0A,$0A,$0A,$0C,$0C,$0C,$0C,$0C
        .byte $0A,$0A,$0A,$0A,$0A,$0A,$0C,$0C
        .byte $0A,$0A,$0A,$0A,$0A,$0A,$0A,$00
        .byte $0A,$00,$00,$0A,$0A,$0A,$00,$0C
        .byte $0C,$0C,$0A,$0A,$00,$0A,$00,$0A   ; bl
        .byte $0C,$0C,$0C,$0A,$00,$00,$00,$0A
        .byte $0C,$0C,$0C,$0A,$00,$0A,$0A,$0A
        .byte $0C,$0C,$0A,$0A,$0A,$0A,$0A,$0C
        .byte $0C,$0A,$0A,$0A,$0A,$0C,$0C,$0C
        .byte $0C,$0A,$0A,$0A,$0C,$0C,$0C,$0C
        .byte $0A,$0A,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0A,$00,$0A,$00,$0A,$00,$0C,$0C   ; br
        .byte $0A,$00,$0A,$00,$00,$0C,$0C,$0C
        .byte $0A,$00,$00,$0A,$00,$0C,$0C,$0C
        .byte $0C,$0A,$0A,$0A,$0A,$00,$0C,$0C
        .byte $0C,$0C,$0C,$0A,$0A,$0A,$00,$0C
        .byte $0C,$0C,$0C,$0C,$0A,$0A,$00,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0A,$00
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C

ui_btn_fire:
        ; Red fire extinguisher ($0D) with a black valve/handle and horn ($00),
        ; white "FD" ($0F) on the body. $0C background.
        .byte $0C,$0C,$0C,$00,$00,$0C,$0C,$0C   ; tl
        .byte $0C,$0C,$0C,$00,$00,$00,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$00,$00,$00,$00
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$00
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0D
        .byte $0C,$0C,$0C,$0C,$0C,$0D,$0D,$0D
        .byte $0C,$0C,$0C,$0D,$0D,$0D,$0D,$0D
        .byte $0C,$0C,$0C,$0D,$0D,$0D,$0D,$0D
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tr
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $00,$00,$00,$0C,$0C,$0C,$0C,$0C
        .byte $00,$00,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0D,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0D,$0D,$0D,$0C,$0C,$0C,$0C,$0C
        .byte $0D,$0D,$0D,$0D,$0D,$0C,$0C,$0C
        .byte $0D,$0D,$0D,$0D,$0D,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0D,$0D,$0F,$0F,$0F   ; bl
        .byte $0C,$0C,$0C,$0D,$0D,$0F,$0D,$0D
        .byte $0C,$0C,$0C,$0D,$0D,$0F,$0F,$0D
        .byte $0C,$0C,$0C,$0D,$0D,$0F,$0D,$0D
        .byte $0C,$0C,$0C,$0D,$0D,$0F,$0D,$0D
        .byte $0C,$0C,$0C,$0D,$0D,$0D,$0D,$0D
        .byte $0C,$0C,$0C,$0C,$0D,$0D,$0D,$0D
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0D,$0F,$0F,$0D,$0D,$0C,$0C,$0C   ; br
        .byte $0D,$0F,$0D,$0F,$0D,$0C,$0C,$0C
        .byte $0D,$0F,$0D,$0F,$0D,$0C,$0C,$0C
        .byte $0D,$0F,$0D,$0F,$0D,$0C,$0C,$0C
        .byte $0D,$0F,$0F,$0D,$0D,$0C,$0C,$0C
        .byte $0D,$0D,$0D,$0D,$0D,$0C,$0C,$0C
        .byte $0D,$0D,$0D,$0D,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C

ui_btn_sport:
        ; Football helmet facing left: red shell ($0D), white stripe ($0F), gray
        ; facemask curving around the front ($05), darker shading at the back
        ; ($04). $0C background.
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tl
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0D,$0D
        .byte $0C,$0C,$0C,$0C,$0D,$0D,$0D,$0D
        .byte $0C,$0C,$0C,$0D,$0D,$0D,$0D,$0F
        .byte $0C,$0C,$0D,$0D,$0D,$0D,$0D,$0F
        .byte $0C,$0C,$0D,$0D,$0D,$0D,$0D,$0D
        .byte $0C,$05,$0D,$0D,$0D,$0D,$0D,$0D
        .byte $0C,$05,$05,$0D,$0D,$0D,$0D,$0D
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tr
        .byte $0D,$0D,$0D,$0C,$0C,$0C,$0C,$0C
        .byte $0D,$0D,$0D,$0D,$0C,$0C,$0C,$0C
        .byte $0D,$0D,$0D,$0D,$0D,$0C,$0C,$0C
        .byte $0F,$0D,$0D,$0D,$0D,$0D,$0C,$0C
        .byte $0F,$0F,$0D,$0D,$0D,$0D,$0C,$0C
        .byte $0D,$0D,$0D,$0D,$0D,$0D,$04,$0C
        .byte $0D,$0D,$0D,$0D,$0D,$04,$04,$0C
        .byte $05,$05,$0C,$0D,$0D,$0D,$0D,$0D   ; bl
        .byte $05,$0C,$0C,$0D,$0D,$0D,$0D,$0D
        .byte $05,$0C,$0C,$0C,$0D,$0D,$0D,$0D
        .byte $05,$05,$0C,$0C,$0D,$0D,$0D,$0D
        .byte $0C,$05,$05,$05,$05,$0D,$0D,$0D
        .byte $0C,$0C,$0C,$05,$05,$05,$0D,$0D
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0D,$0D,$0D,$0D,$0D,$04,$04,$0C   ; br
        .byte $0D,$0D,$0D,$0D,$0D,$04,$04,$0C
        .byte $0D,$0D,$0D,$0D,$04,$04,$0C,$0C
        .byte $0D,$0D,$0D,$04,$04,$0C,$0C,$0C
        .byte $0D,$0D,$04,$04,$0C,$0C,$0C,$0C
        .byte $0D,$04,$04,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C

ui_btn_sea:
        ; Ship's anchor ($08): ring at top, horizontal stock, vertical shank,
        ; and curved arms/flukes at the bottom. $0C background.
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$08   ; tl
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$08,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$08,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$08
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$08
        .byte $0C,$0C,$08,$08,$08,$08,$08,$08
        .byte $0C,$0C,$08,$08,$08,$08,$08,$08
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$08
        .byte $08,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tr
        .byte $0C,$08,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$08,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $08,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $08,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $08,$08,$08,$08,$08,$08,$0C,$0C
        .byte $08,$08,$08,$08,$08,$08,$0C,$0C
        .byte $08,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$08   ; bl
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$08
        .byte $0C,$0C,$08,$0C,$0C,$0C,$0C,$08
        .byte $0C,$0C,$08,$08,$0C,$0C,$0C,$08
        .byte $0C,$0C,$0C,$08,$08,$0C,$0C,$08
        .byte $0C,$0C,$0C,$0C,$08,$08,$0C,$08
        .byte $0C,$0C,$0C,$0C,$08,$08,$08,$08
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $08,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; br
        .byte $08,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $08,$0C,$0C,$0C,$0C,$08,$0C,$0C
        .byte $08,$0C,$0C,$0C,$08,$08,$0C,$0C
        .byte $08,$0C,$0C,$08,$08,$0C,$0C,$0C
        .byte $08,$0C,$08,$08,$0C,$0C,$0C,$0C
        .byte $08,$08,$08,$08,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C

ui_btn_coalpp:
        ; Coal power plant: red building ($0D) with brown roof/base and three
        ; brown smokestacks ($04) puffing gray smoke ($0B), lit windows ($0A),
        ; on green grass ($02). $0C sky.
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tl
        .byte $0C,$0C,$0B,$0C,$0C,$0C,$0B,$0C
        .byte $0C,$0C,$0B,$0B,$0C,$0C,$0B,$0B
        .byte $0C,$0C,$0C,$0B,$0C,$0C,$0C,$0B
        .byte $0C,$0C,$04,$04,$0C,$0C,$04,$04
        .byte $0C,$0C,$04,$04,$0C,$0C,$04,$04
        .byte $0C,$0C,$04,$04,$0C,$0C,$04,$04
        .byte $0C,$0C,$04,$04,$0C,$0C,$04,$04
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tr
        .byte $0C,$0C,$0B,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0B,$0B,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0B,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$04,$04,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$04,$04,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$04,$04,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$04,$04,$0C,$0C,$0C,$0C
        .byte $0C,$04,$04,$04,$04,$04,$04,$04   ; bl
        .byte $0C,$0D,$0D,$0D,$0D,$0D,$0D,$0D
        .byte $0C,$0D,$0D,$0D,$0D,$0D,$0D,$0D
        .byte $0C,$0D,$0D,$0A,$0D,$0D,$0A,$0D
        .byte $0C,$0D,$0D,$0D,$0D,$0D,$0D,$0D
        .byte $0C,$04,$04,$04,$04,$04,$04,$04
        .byte $02,$02,$02,$02,$02,$02,$02,$02
        .byte $02,$02,$02,$02,$02,$02,$02,$02
        .byte $04,$04,$04,$04,$04,$04,$04,$0C   ; br
        .byte $0D,$0D,$0D,$0D,$0D,$0D,$0D,$0C
        .byte $0D,$0D,$0D,$0D,$0D,$0D,$0D,$0C
        .byte $0D,$0A,$0D,$0D,$0A,$0D,$0D,$0C
        .byte $0D,$0D,$0D,$0D,$0D,$0D,$0D,$0C
        .byte $04,$04,$04,$04,$04,$04,$04,$0C
        .byte $02,$02,$02,$02,$02,$02,$02,$02
        .byte $02,$02,$02,$02,$02,$02,$02,$02

ui_btn_nuclearpp:
        ; Nuclear plant: white cooling tower ($0F) with $0B outline puffing gray
        ; steam ($0B), a small brown reactor building ($04) with a lit window
        ; ($0A), on green grass ($02). $0C sky.
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tl
        .byte $0C,$0C,$0C,$0C,$0C,$0B,$0B,$0B
        .byte $0C,$0C,$0C,$0C,$0B,$0B,$0B,$0B
        .byte $0C,$0C,$0C,$0C,$0C,$0B,$0B,$0B
        .byte $0C,$0C,$0C,$0C,$0B,$0F,$0F,$0F
        .byte $0C,$0C,$0C,$0C,$0B,$0F,$0F,$0F
        .byte $0C,$0C,$0C,$0C,$0C,$0B,$0F,$0F
        .byte $0C,$0C,$0C,$0C,$0C,$0B,$0F,$0F
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tr
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0B,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0F,$0B,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0F,$0B,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0B,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0B,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0B,$0F,$0F,$0F   ; bl
        .byte $0C,$0C,$0C,$0C,$0B,$0F,$0F,$0F
        .byte $0C,$0C,$0C,$0B,$0F,$0F,$0F,$0F
        .byte $0C,$0C,$0C,$0B,$0F,$0F,$0F,$0F
        .byte $0C,$0C,$0C,$0B,$0F,$0F,$0F,$0F
        .byte $0C,$0C,$0C,$0B,$0F,$0F,$0F,$0F
        .byte $02,$02,$02,$02,$02,$02,$02,$02
        .byte $02,$02,$02,$02,$02,$02,$02,$02
        .byte $0F,$0B,$0C,$0C,$0C,$0C,$0C,$0C   ; br
        .byte $0F,$0B,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0F,$0F,$0B,$0C,$0C,$0C,$0C,$0C
        .byte $0F,$0F,$0B,$0C,$04,$04,$04,$0C
        .byte $0F,$0F,$0B,$0C,$04,$0A,$04,$0C
        .byte $0F,$0F,$0B,$0C,$04,$04,$04,$0C
        .byte $02,$02,$02,$02,$02,$02,$02,$02
        .byte $02,$02,$02,$02,$02,$02,$02,$02

ui_btn_air:
        ; Airport: top-down white airplane ($0F) on a dark-blue tarmac ($01).
        .byte $01,$01,$01,$01,$01,$01,$01,$01   ; tl
        .byte $01,$01,$01,$01,$01,$01,$01,$0F
        .byte $01,$01,$01,$01,$01,$01,$01,$0F
        .byte $01,$01,$01,$01,$01,$01,$0F,$0F
        .byte $01,$01,$01,$01,$01,$01,$0F,$0F
        .byte $01,$01,$01,$01,$01,$01,$0F,$0F
        .byte $01,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $01,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $01,$01,$01,$01,$01,$01,$01,$01   ; tr
        .byte $0F,$01,$01,$01,$01,$01,$01,$01
        .byte $0F,$01,$01,$01,$01,$01,$01,$01
        .byte $0F,$0F,$01,$01,$01,$01,$01,$01
        .byte $0F,$0F,$01,$01,$01,$01,$01,$01
        .byte $0F,$0F,$01,$01,$01,$01,$01,$01
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$01
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$01
        .byte $01,$01,$01,$01,$01,$01,$0F,$0F   ; bl
        .byte $01,$01,$01,$01,$01,$01,$01,$0F
        .byte $01,$01,$01,$01,$01,$01,$01,$0F
        .byte $01,$01,$01,$01,$0F,$0F,$0F,$0F
        .byte $01,$01,$01,$01,$0F,$0F,$0F,$0F
        .byte $01,$01,$01,$01,$01,$01,$01,$0F
        .byte $01,$01,$01,$01,$01,$01,$01,$01
        .byte $01,$01,$01,$01,$01,$01,$01,$01
        .byte $0F,$0F,$01,$01,$01,$01,$01,$01   ; br
        .byte $0F,$01,$01,$01,$01,$01,$01,$01
        .byte $0F,$01,$01,$01,$01,$01,$01,$01
        .byte $0F,$0F,$0F,$0F,$01,$01,$01,$01
        .byte $0F,$0F,$0F,$0F,$01,$01,$01,$01
        .byte $0F,$01,$01,$01,$01,$01,$01,$01
        .byte $01,$01,$01,$01,$01,$01,$01,$01
        .byte $01,$01,$01,$01,$01,$01,$01,$01

ui_btn_special:
        ; Special: a dark-gray question mark ($0B) on the $0C panel background.
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tl
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0B,$0B
        .byte $0C,$0C,$0C,$0C,$0C,$0B,$0B,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0B
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; tr
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0B,$0B,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0B,$0B,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0B,$0B,$0C,$0C,$0C,$0C,$0C
        .byte $0B,$0B,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0B,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0B   ; bl
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0B
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0B
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0B
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0B,$0C,$0C,$0C,$0C,$0C,$0C,$0C   ; br
        .byte $0B,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0B,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0B,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C
        .byte $0C,$0C,$0C,$0C,$0C,$0C,$0C,$0C

ui_tiles_end:
        .cerror ui_tiles_end - ui_tiles_start != UI_TILE_ASSET_SIZE, "UI tile asset size mismatch"
