;=======================================================================================
; UI/FCM tile and glyph data.
;
; Compiles standalone into the `uitiles` asset (loaded from disk at boot). The
; payload is laid out at the offsets in shared/ui_tile_layout.asm; tileloader.asm
; DMAs from those same offsets. The ui_glyph_* bitmaps MUST stay in
; UI_TEXT_A..UI_TEXT_COLON order, since the index/offsets are generated by loops.
;
; Record format:
;   .word tile id
;   .word payload size
;   .byte payload bytes
;=======================================================================================

        .cpu "45gs02"
        .include "../platform.asm"
        .include "../shared/ui_tile_layout.asm"

; Origin is irrelevant: position-independent data. It only sets the 2-byte PRG
; load-address header, which the boot loader strips (DMAs body from staging+2).
; $0000 so no reader infers a real address.
        * = $0000

ui_tiles_start:

; Text glyph border colour. Set to $0C (light grey, same as UI_TILE_PANEL
; and UI_TILE_MENU) so glyphs blend into the panel + chrome bar instead of
; punching cyan rectangles around each letter on the popup. Foreground is
; black -- baked in at asset-build time.
UI_TEXT_BG = $0C
UI_TEXT_FG = $00

UI_TEXT_ROW .macro p0, p1, p2, p3, p4
        .byte UI_TEXT_BG, \p0, \p1, \p2, \p3, \p4, UI_TEXT_BG, UI_TEXT_BG
.endmacro

; Commodore-style glyph macros. CBM_ROW takes one byte (8 bits, MSB first) and
; expands it into 8 palette indices (UI_TEXT_FG where the bit is 1, UI_TEXT_BG
; where 0). CBM_GLYPH stacks 8 rows of CBM_ROW into a full 8x8 FCM cell.
;
; The byte data matches the standard C64 character ROM bitmaps for uppercase
; A-Z, 0-9 and a handful of punctuation. Copy/paste from any C64 charset table
; (e.g. CHARGEN at $D000 in the C64 memory map).
CBM_ROW .macro b
        .byte (\b) & $80 ? UI_TEXT_FG : UI_TEXT_BG
        .byte (\b) & $40 ? UI_TEXT_FG : UI_TEXT_BG
        .byte (\b) & $20 ? UI_TEXT_FG : UI_TEXT_BG
        .byte (\b) & $10 ? UI_TEXT_FG : UI_TEXT_BG
        .byte (\b) & $08 ? UI_TEXT_FG : UI_TEXT_BG
        .byte (\b) & $04 ? UI_TEXT_FG : UI_TEXT_BG
        .byte (\b) & $02 ? UI_TEXT_FG : UI_TEXT_BG
        .byte (\b) & $01 ? UI_TEXT_FG : UI_TEXT_BG
.endmacro

CBM_GLYPH .macro b0, b1, b2, b3, b4, b5, b6, b7
        #CBM_ROW \b0
        #CBM_ROW \b1
        #CBM_ROW \b2
        #CBM_ROW \b3
        #CBM_ROW \b4
        #CBM_ROW \b5
        #CBM_ROW \b6
        #CBM_ROW \b7
.endmacro

UI_TILE_RECORD .macro index
.endmacro

#UI_TILE_RECORD UI_TILE_PANEL
ui_data_panel:
        .fill 64, $0C

#UI_TILE_RECORD UI_TILE_MENU
ui_data_menu:
        .fill 64, $0C       ; light grey -- matches UI_TILE_PANEL and UI_TEXT_BG

#UI_TILE_RECORD UI_TILE_STATUS_LIGHT
ui_data_status_light:
        .fill 64, $0C

#UI_TILE_RECORD UI_TILE_STATUS_DARK
ui_data_status_dark:
        .fill 64, $0C

#UI_TILE_RECORD UI_TILE_FRAME
ui_data_frame:
        .fill 64, $08

#UI_TILE_RECORD UI_TILE_BOTTOM
ui_data_bottom:
        .byte $08,$08,$08,$08,$08,$08,$08,$08
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $08,$08,$08,$08,$08,$08,$08,$08

#UI_TILE_RECORD UI_TEXT_A
ui_glyph_a:
        #CBM_GLYPH $18, $3C, $66, $7E, $66, $66, $66, $00

#UI_TILE_RECORD UI_TEXT_B
ui_glyph_b:
        #CBM_GLYPH $7C, $66, $66, $7C, $66, $66, $7C, $00

#UI_TILE_RECORD UI_TEXT_C
ui_glyph_c:
        #CBM_GLYPH $3C, $66, $60, $60, $60, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_D
ui_glyph_d:
        #CBM_GLYPH $78, $6C, $66, $66, $66, $6C, $78, $00

#UI_TILE_RECORD UI_TEXT_E
ui_glyph_e:
        #CBM_GLYPH $7E, $60, $60, $78, $60, $60, $7E, $00

#UI_TILE_RECORD UI_TEXT_F
ui_glyph_f:
        #CBM_GLYPH $7E, $60, $60, $78, $60, $60, $60, $00

#UI_TILE_RECORD UI_TEXT_G
ui_glyph_g:
        #CBM_GLYPH $3C, $66, $60, $6E, $66, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_H
ui_glyph_h:
        #CBM_GLYPH $66, $66, $66, $7E, $66, $66, $66, $00

#UI_TILE_RECORD UI_TEXT_I
ui_glyph_i:
        #CBM_GLYPH $3C, $18, $18, $18, $18, $18, $3C, $00

#UI_TILE_RECORD UI_TEXT_J
ui_glyph_j:
        #CBM_GLYPH $1E, $0C, $0C, $0C, $0C, $6C, $38, $00

#UI_TILE_RECORD UI_TEXT_K
ui_glyph_k:
        #CBM_GLYPH $66, $6C, $78, $70, $78, $6C, $66, $00

#UI_TILE_RECORD UI_TEXT_L
ui_glyph_l:
        #CBM_GLYPH $60, $60, $60, $60, $60, $60, $7E, $00

#UI_TILE_RECORD UI_TEXT_M
ui_glyph_m:
        #CBM_GLYPH $63, $77, $7F, $6B, $63, $63, $63, $00

#UI_TILE_RECORD UI_TEXT_N
ui_glyph_n:
        #CBM_GLYPH $66, $76, $7E, $7E, $6E, $66, $66, $00

#UI_TILE_RECORD UI_TEXT_O
ui_glyph_o:
        #CBM_GLYPH $3C, $66, $66, $66, $66, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_P
ui_glyph_p:
        #CBM_GLYPH $7C, $66, $66, $7C, $60, $60, $60, $00

#UI_TILE_RECORD UI_TEXT_Q
ui_glyph_q:
        #CBM_GLYPH $3C, $66, $66, $66, $66, $3C, $0E, $00

#UI_TILE_RECORD UI_TEXT_R
ui_glyph_r:
        #CBM_GLYPH $7C, $66, $66, $7C, $78, $6C, $66, $00

#UI_TILE_RECORD UI_TEXT_S
ui_glyph_s:
        #CBM_GLYPH $3C, $66, $60, $3C, $06, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_T
ui_glyph_t:
        #CBM_GLYPH $7E, $18, $18, $18, $18, $18, $18, $00

#UI_TILE_RECORD UI_TEXT_U
ui_glyph_u:
        #CBM_GLYPH $66, $66, $66, $66, $66, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_V
ui_glyph_v:
        #CBM_GLYPH $66, $66, $66, $66, $66, $3C, $18, $00

#UI_TILE_RECORD UI_TEXT_W
ui_glyph_w:
        #CBM_GLYPH $63, $63, $63, $6B, $7F, $77, $63, $00

#UI_TILE_RECORD UI_TEXT_X
ui_glyph_x:
        #CBM_GLYPH $66, $66, $3C, $18, $3C, $66, $66, $00

#UI_TILE_RECORD UI_TEXT_Y
ui_glyph_y:
        #CBM_GLYPH $66, $66, $66, $3C, $18, $18, $18, $00

#UI_TILE_RECORD UI_TEXT_Z
ui_glyph_z:
        #CBM_GLYPH $7E, $06, $0C, $18, $30, $60, $7E, $00

#UI_TILE_RECORD UI_TEXT_0
ui_glyph_0:
        #CBM_GLYPH $3C, $66, $6E, $7E, $76, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_1
ui_glyph_1:
        #CBM_GLYPH $18, $38, $18, $18, $18, $18, $7E, $00

#UI_TILE_RECORD UI_TEXT_2
ui_glyph_2:
        #CBM_GLYPH $3C, $66, $06, $0C, $30, $60, $7E, $00

#UI_TILE_RECORD UI_TEXT_3
ui_glyph_3:
        #CBM_GLYPH $3C, $66, $06, $1C, $06, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_4
ui_glyph_4:
        #CBM_GLYPH $06, $0E, $1E, $66, $7F, $06, $06, $00

#UI_TILE_RECORD UI_TEXT_5
ui_glyph_5:
        #CBM_GLYPH $7E, $60, $7C, $06, $06, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_6
ui_glyph_6:
        #CBM_GLYPH $3C, $66, $60, $7C, $66, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_7
ui_glyph_7:
        #CBM_GLYPH $7E, $66, $0C, $18, $18, $18, $18, $00

#UI_TILE_RECORD UI_TEXT_8
ui_glyph_8:
        #CBM_GLYPH $3C, $66, $66, $3C, $66, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_9
ui_glyph_9:
        #CBM_GLYPH $3C, $66, $66, $3E, $06, $66, $3C, $00

#UI_TILE_RECORD UI_TEXT_COMMA
ui_glyph_comma:
        #CBM_GLYPH $00, $00, $00, $00, $00, $18, $18, $30

#UI_TILE_RECORD UI_TEXT_DOT
ui_glyph_dot:
        #CBM_GLYPH $00, $00, $00, $00, $00, $00, $18, $18

#UI_TILE_RECORD UI_TEXT_DOLLAR
ui_glyph_dollar:
        #CBM_GLYPH $18, $3E, $60, $3C, $06, $7C, $18, $00

#UI_TILE_RECORD UI_TEXT_COLON
ui_glyph_colon:
        #CBM_GLYPH $00, $00, $18, $18, $00, $18, $18, $00

;=======================================================================================
; Toolbar buttons: 16 consecutive 2x2 tiles, each four 8x8 chars in tl, tr, bl,
; br order. One byte per pixel, low nibble = palette index. bulldozer and road
; have art; the rest reuse the placeholder box (#PLACEHOLDER_BOX) until drawn.
; Replace a #PLACEHOLDER_BOX line with explicit .byte rows to give that button a
; real icon. Order must match the UI_BTN_* enum in shared/ui_tile_layout.asm.
;=======================================================================================

; A 2x2 button box: $0B border, $05 interior.
PLACEHOLDER_BOX .macro
        .byte $0B,$0B,$0B,$0B,$0B,$0B,$0B,$0B   ; tl
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$0B,$0B,$0B,$0B,$0B,$0B,$0B   ; tr
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $0B,$05,$05,$05,$05,$05,$05,$05   ; bl
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$05,$05,$05,$05,$05,$05,$05
        .byte $0B,$0B,$0B,$0B,$0B,$0B,$0B,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B   ; br
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $05,$05,$05,$05,$05,$05,$05,$0B
        .byte $0B,$0B,$0B,$0B,$0B,$0B,$0B,$0B
.endmacro


ui_btn_bulldozer:
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $1D, $1D, $1D, $1D, $1D, $1D, $1D
.BYTE $0E, $0E, $0E, $1C, $0E, $0E, $0E, $1C
.BYTE $0E, $0E, $0E, $1C, $0E, $0E, $0E, $1C
.BYTE $0E, $0E, $0E, $1C, $1D, $0E, $0E, $1C
.BYTE $0E, $0E, $0E, $1C, $1D, $0E, $0E, $0E
.BYTE $0E, $0E, $1D, $1C, $1D, $1D, $1C, $1C

.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $1D, $1D, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $1D, $0E, $0E, $0E, $0E, $0F
.BYTE $1C, $0E, $1D, $0E, $0E, $0B, $0E, $0F
.BYTE $1C, $1C, $1C, $1C, $0E, $0B, $0E, $0F
.BYTE $1C, $1C, $1C, $1C, $1C, $0B, $0E, $0F

.BYTE $0E, $1C, $1C, $1C, $1C, $1C, $1C, $1C
.BYTE $0E, $1C, $1C, $1C, $1C, $1C, $1C, $1C
.BYTE $0E, $0E, $1C, $0B, $04, $0B, $04, $0B
.BYTE $0E, $0E, $04, $1C, $1C, $04, $04, $04
.BYTE $0E, $0E, $0B, $1C, $1C, $04, $1C, $04
.BYTE $0E, $0E, $0E, $04, $0B, $04, $0B, $04
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $00, $00, $00, $00, $00, $00, $00, $00

.BYTE $1C, $1C, $1C, $1C, $1C, $0B, $0E, $0F
.BYTE $1C, $1C, $1C, $1C, $1C, $0B, $0E, $0F
.BYTE $04, $0B, $04, $1C, $1C, $0B, $0E, $0F
.BYTE $04, $04, $04, $0B, $0E, $0B, $05, $0F
.BYTE $1C, $1C, $04, $04, $0E, $0E, $0B, $0F
.BYTE $0B, $04, $0B, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $00, $00, $00, $00, $00, $00, $00, $0F

ui_btn_road:
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0B, $0B, $0B, $0B, $0B, $0B, $0B
.BYTE $0E, $05, $05, $05, $05, $05, $05, $05
.BYTE $0E, $0F, $0F, $0F, $0F, $05, $0F, $0F

.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0B, $0B, $0B, $0B, $0B, $0B, $0B, $0F
.BYTE $05, $05, $05, $05, $05, $05, $05, $0F
.BYTE $0F, $0F, $05, $0F, $0F, $0F, $0F, $0F

.BYTE $0E, $0F, $0F, $0F, $0F, $05, $0F, $0F
.BYTE $0E, $05, $05, $05, $05, $05, $05, $05
.BYTE $0E, $00, $00, $00, $00, $00, $00, $00
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $00, $00, $00, $00, $00, $00, $00, $00

.BYTE $0F, $0F, $05, $0F, $0F, $0F, $0F, $0F
.BYTE $05, $05, $05, $05, $05, $05, $05, $0F
.BYTE $00, $00, $00, $00, $00, $00, $00, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $00, $00, $00, $00, $00, $00, $00, $0F

ui_btn_rail:
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $04, $04, $05, $0E, $04, $04, $05
.BYTE $0E, $04, $04, $05, $0E, $04, $04, $05
.BYTE $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
.BYTE $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
.BYTE $0E, $04, $04, $05, $0E, $04, $04, $05
.BYTE $0E, $04, $04, $05, $0E, $04, $04, $05

.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $04, $04, $05, $0E, $04, $04, $0F
.BYTE $0E, $04, $04, $05, $0E, $04, $04, $0F
.BYTE $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
.BYTE $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
.BYTE $0E, $04, $04, $05, $0E, $04, $04, $0F
.BYTE $0E, $04, $04, $05, $0E, $04, $04, $0F

.BYTE $0E, $04, $04, $05, $0E, $04, $04, $05
.BYTE $0E, $04, $04, $05, $0E, $04, $04, $05
.BYTE $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
.BYTE $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
.BYTE $0E, $04, $04, $05, $0E, $04, $04, $05
.BYTE $0E, $04, $04, $05, $0E, $04, $04, $05
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $00, $00, $00, $00, $00, $00, $00, $00

.BYTE $0E, $04, $04, $05, $0E, $04, $04, $0F
.BYTE $0E, $04, $04, $05, $0E, $04, $04, $0F
.BYTE $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
.BYTE $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
.BYTE $0E, $04, $04, $05, $0E, $04, $04, $0F
.BYTE $0E, $04, $04, $05, $0E, $04, $04, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $00, $00, $00, $00, $00, $00, $00, $0F

ui_btn_power:
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $04, $0E, $0E, $0E, $0E
.BYTE $0E, $04, $04, $04, $04, $04, $0E, $0E
.BYTE $0E, $0E, $0E, $04, $0E, $0E, $0E, $0E
.BYTE $0E, $04, $04, $04, $04, $04, $0E, $0E
.BYTE $0E, $0E, $0E, $04, $0E, $0E, $04, $04
.BYTE $0E, $0E, $0E, $04, $0E, $0E, $0E, $0E

.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $04, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $04, $04, $04, $0E, $0E, $0E, $0E, $0F
.BYTE $04, $0E, $0E, $0E, $0E, $0E, $0E, $0F

.BYTE $0E, $0E, $0E, $04, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $04, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $04, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $04, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $04, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $04, $0E, $0E, $0E, $0E
.BYTE $02, $02, $02, $04, $02, $02, $02, $02
.BYTE $00, $00, $00, $00, $00, $00, $00, $00

.BYTE $04, $0E, $0E, $0E, $04, $0E, $0E, $0F
.BYTE $04, $0E, $0E, $0E, $04, $0E, $0E, $0F
.BYTE $04, $0E, $0E, $0E, $04, $0E, $0E, $0F
.BYTE $04, $0E, $0E, $0E, $04, $0E, $0E, $0F
.BYTE $04, $0E, $0E, $0E, $04, $0E, $0E, $0F
.BYTE $04, $0E, $0E, $0E, $04, $0E, $0E, $0F
.BYTE $02, $02, $02, $02, $02, $02, $02, $0F
.BYTE $00, $00, $00, $00, $00, $00, $00, $0F

ui_btn_park:
.BYTE $06, $06, $06, $06, $06, $06, $06, $06
.BYTE $06, $06, $06, $03, $02, $03, $06, $06
.BYTE $06, $06, $02, $07, $02, $03, $03, $06
.BYTE $02, $02, $07, $07, $07, $02, $03, $06
.BYTE $02, $02, $07, $07, $03, $03, $03, $03
.BYTE $03, $02, $03, $07, $02, $03, $03, $02
.BYTE $03, $02, $03, $02, $03, $02, $02, $03
.BYTE $06, $06, $03, $03, $06, $03, $03, $02

.BYTE $06, $06, $06, $06, $06, $06, $06, $0F
.BYTE $06, $06, $06, $06, $06, $06, $06, $0F
.BYTE $06, $06, $06, $06, $06, $06, $06, $0F
.BYTE $06, $06, $06, $06, $06, $06, $06, $0F
.BYTE $03, $06, $06, $06, $06, $06, $06, $0F
.BYTE $02, $06, $06, $06, $06, $06, $06, $0F
.BYTE $06, $06, $06, $06, $06, $06, $06, $0F
.BYTE $06, $06, $06, $06, $06, $06, $06, $0F

.BYTE $06, $03, $03, $02, $16, $03, $02, $02
.BYTE $06, $06, $06, $02, $03, $04, $06, $06
.BYTE $06, $06, $06, $04, $16, $06, $06, $06
.BYTE $06, $06, $06, $04, $16, $06, $06, $06
.BYTE $06, $06, $06, $04, $16, $06, $06, $06
.BYTE $06, $06, $16, $04, $16, $16, $06, $06
.BYTE $02, $02, $02, $02, $02, $02, $02, $02
.BYTE $00, $00, $00, $00, $0B, $00, $00, $00

.BYTE $06, $06, $06, $06, $06, $06, $06, $0F
.BYTE $06, $06, $06, $06, $06, $06, $06, $0F
.BYTE $06, $06, $06, $06, $06, $06, $06, $0F
.BYTE $05, $05, $05, $05, $05, $06, $06, $0F
.BYTE $05, $05, $05, $05, $05, $06, $06, $0F
.BYTE $05, $06, $06, $06, $05, $06, $06, $0F
.BYTE $02, $02, $02, $02, $02, $02, $02, $0F
.BYTE $00, $00, $00, $00, $00, $00, $00, $0F

ui_btn_residential:
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $09, $0E, $0E, $09, $09, $09
.BYTE $0E, $0E, $09, $0E, $09, $09, $09, $09
.BYTE $0E, $0E, $09, $09, $09, $0F, $0F, $0F
.BYTE $0E, $0E, $09, $09, $0F, $0F, $0F, $0F
.BYTE $0E, $09, $09, $0F, $0F, $0F, $0F, $0F

.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $00, $00, $00, $0E, $0E, $0F
.BYTE $0E, $0E, $00, $0E, $0E, $00, $0E, $0F
.BYTE $0E, $0E, $00, $00, $00, $0E, $0E, $0F
.BYTE $09, $0E, $00, $0E, $0E, $00, $0E, $0F
.BYTE $09, $09, $00, $0E, $0E, $00, $0E, $0F
.BYTE $0F, $09, $09, $0E, $0E, $0E, $0E, $0F
.BYTE $0F, $0F, $09, $09, $0E, $0E, $0E, $0F

.BYTE $09, $09, $0F, $0F, $0F, $09, $0F, $09
.BYTE $0E, $0F, $0F, $0F, $0F, $0F, $0F, $0F
.BYTE $0E, $0F, $0F, $0F, $0F, $0F, $0F, $0F
.BYTE $0E, $0F, $0F, $0F, $0F, $09, $0F, $09
.BYTE $0E, $0F, $0F, $0F, $0F, $0F, $0F, $0F
.BYTE $0E, $0F, $0F, $0F, $0F, $0F, $0F, $0F
.BYTE $02, $02, $02, $02, $02, $02, $02, $02
.BYTE $0B, $0B, $0B, $0B, $0B, $0B, $0B, $0B

.BYTE $0F, $0F, $0F, $09, $09, $0E, $0E, $0F
.BYTE $0F, $0F, $0F, $04, $0E, $0E, $0E, $0F
.BYTE $0F, $0F, $0F, $04, $0E, $0E, $0E, $0F
.BYTE $0F, $0F, $0F, $04, $0E, $0E, $0E, $0F
.BYTE $0F, $0F, $0F, $04, $0E, $0E, $0E, $0F
.BYTE $0F, $0F, $0F, $04, $0E, $0E, $0E, $0F
.BYTE $02, $02, $02, $02, $02, $02, $02, $0F
.BYTE $0B, $0B, $0B, $0B, $0B, $0B, $0B, $0F

ui_btn_commercial:
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $08, $08, $08, $08, $08, $08, $01
.BYTE $0E, $08, $0F, $08, $08, $0F, $08, $01
.BYTE $0E, $08, $08, $08, $08, $08, $08, $01
.BYTE $0E, $08, $0F, $08, $08, $0F, $08, $01
.BYTE $0E, $08, $08, $08, $08, $08, $08, $01

.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $00, $00, $0B, $0E, $0F
.BYTE $0E, $0E, $00, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $00, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $00, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $00, $00, $0B, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F

.BYTE $0E, $08, $0F, $08, $08, $0F, $08, $01
.BYTE $0E, $08, $08, $08, $08, $08, $08, $08
.BYTE $0E, $08, $0F, $08, $08, $0F, $08, $08
.BYTE $0E, $08, $08, $08, $08, $08, $08, $08
.BYTE $0E, $08, $0F, $08, $08, $0F, $08, $08
.BYTE $0E, $08, $08, $08, $08, $08, $08, $08
.BYTE $02, $02, $02, $02, $02, $02, $02, $02
.BYTE $00, $00, $00, $00, $00, $00, $00, $00

.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $08, $08, $08, $08, $08, $01, $0E, $0F
.BYTE $0F, $08, $08, $0F, $08, $01, $0E, $0F
.BYTE $08, $08, $08, $08, $08, $01, $0E, $0F
.BYTE $0F, $08, $08, $0F, $08, $01, $0E, $0F
.BYTE $08, $08, $08, $08, $08, $01, $0E, $0F
.BYTE $02, $02, $02, $02, $02, $02, $02, $0F
.BYTE $00, $00, $00, $00, $00, $00, $00, $00

ui_btn_industrial:
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $09, $0B, $0E, $0E
.BYTE $0E, $0E, $0E, $0B, $09, $0B, $0E, $22
.BYTE $0E, $0E, $0E, $0B, $0B, $0E, $05, $22
.BYTE $0E, $0E, $0E, $04, $04, $0E, $22, $05
.BYTE $0E, $0E, $0E, $04, $04, $0E, $04, $04
.BYTE $0E, $0E, $0E, $04, $04, $0E, $04, $04
.BYTE $0E, $0E, $0E, $04, $04, $0E, $04, $04

.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $04, $0E, $0E, $00, $00, $00, $0E, $0F
.BYTE $04, $0E, $0E, $0E, $00, $0E, $0E, $0F
.BYTE $09, $0E, $0E, $0E, $00, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $00, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $00, $00, $00, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F

.BYTE $0E, $0E, $0E, $04, $04, $0E, $04, $04
.BYTE $0E, $05, $05, $05, $05, $05, $05, $05
.BYTE $0E, $05, $0F, $05, $0F, $05, $0F, $05
.BYTE $0E, $05, $0F, $05, $0F, $05, $0F, $05
.BYTE $0E, $05, $05, $05, $05, $05, $05, $05
.BYTE $0E, $05, $05, $05, $05, $05, $05, $05
.BYTE $02, $02, $02, $02, $02, $02, $02, $02
.BYTE $00, $00, $00, $00, $00, $00, $00, $00

.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $05, $05, $05, $05, $05, $05, $0E, $0F
.BYTE $0F, $05, $0F, $05, $05, $05, $0E, $0F
.BYTE $0F, $05, $0F, $05, $05, $05, $0E, $0F
.BYTE $05, $05, $05, $05, $05, $05, $0E, $0F
.BYTE $05, $05, $05, $05, $05, $05, $0E, $0F
.BYTE $02, $02, $02, $02, $02, $02, $02, $0F
.BYTE $00, $00, $00, $00, $00, $00, $00, $0F

ui_btn_police:
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0A
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $06
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $06, $0A
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $06, $0A
.BYTE $0E, $0E, $0E, $0E, $0E, $06, $0A, $0A
.BYTE $0E, $0E, $06, $06, $06, $06, $0A, $0A
.BYTE $06, $06, $0A, $0A, $0F, $0F, $0A, $0A
.BYTE $0E, $0A, $0A, $0A, $0F, $00, $0F, $0A

.BYTE $0A, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $06, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0A, $06, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0A, $06, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0A, $0A, $06, $0E, $0E, $0E, $0E, $0F
.BYTE $0A, $0A, $0A, $06, $06, $06, $0E, $0F
.BYTE $0A, $0F, $0F, $0A, $0A, $0A, $06, $0F
.BYTE $0A, $0F, $00, $0F, $0A, $0A, $00, $0F

.BYTE $0E, $0E, $0A, $0A, $0F, $0A, $0F, $0A
.BYTE $0E, $0E, $0E, $0A, $0F, $0F, $00, $0A
.BYTE $0E, $0E, $0E, $0A, $0F, $0B, $0A, $0A
.BYTE $0E, $0E, $06, $0A, $0B, $0A, $0A, $06
.BYTE $0E, $06, $0A, $0A, $0A, $06, $0E, $0E
.BYTE $0E, $06, $0A, $0A, $0E, $0E, $0E, $0E
.BYTE $0E, $06, $06, $0E, $0E, $0E, $0E, $0E
.BYTE $00, $00, $00, $00, $00, $00, $00, $00

.BYTE $0A, $0F, $0A, $0F, $06, $00, $0E, $0F
.BYTE $0A, $0F, $0A, $0F, $00, $0E, $0E, $0F
.BYTE $0A, $0F, $0F, $00, $00, $0E, $0E, $0F
.BYTE $06, $00, $00, $0A, $0A, $00, $0E, $0F
.BYTE $0E, $0E, $06, $0A, $0A, $0A, $00, $0F
.BYTE $0E, $0E, $0E, $0E, $0A, $0A, $00, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $06, $06, $0F
.BYTE $00, $00, $00, $00, $00, $00, $00, $0F

ui_btn_fire:
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $00, $00
.BYTE $0E, $0E, $0E, $0E, $00, $00, $00, $00
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $00, $00
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0D
.BYTE $0E, $0E, $0E, $0E, $0E, $0D, $0D, $0D
.BYTE $0E, $0E, $0E, $0D, $0D, $0D, $0D, $0D
.BYTE $0E, $0E, $0E, $0D, $0D, $0D, $0D, $0D

.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $00, $00, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $00, $00, $00, $00, $0E, $0E, $0E, $0F
.BYTE $00, $00, $0E, $0E, $00, $0E, $0E, $0F
.BYTE $0D, $0E, $0E, $0E, $0E, $00, $0E, $0F
.BYTE $0D, $0D, $0D, $0E, $0E, $00, $0E, $0F
.BYTE $0D, $0D, $0D, $0D, $0D, $0E, $0E, $0F
.BYTE $0D, $0D, $0D, $0D, $0D, $0E, $0E, $0F

.BYTE $0E, $0E, $0E, $0D, $0D, $0F, $0F, $0F
.BYTE $0E, $0E, $0E, $0D, $0D, $0F, $0B, $0B
.BYTE $0E, $0E, $0E, $0D, $0D, $0F, $0F, $0D
.BYTE $0E, $0E, $0E, $0D, $0D, $0F, $0B, $0D
.BYTE $0E, $0E, $0E, $0D, $0D, $0F, $0D, $0D
.BYTE $0E, $0E, $0E, $0D, $0D, $0B, $0D, $0D
.BYTE $0E, $0E, $0E, $0D, $0D, $0D, $0D, $0D
.BYTE $00, $00, $00, $00, $00, $00, $00, $00

.BYTE $0D, $0F, $0F, $0D, $0D, $0E, $0E, $0F
.BYTE $0D, $0F, $0B, $0F, $0D, $0E, $0E, $0F
.BYTE $0D, $0F, $0D, $0F, $0D, $0E, $0E, $0F
.BYTE $0D, $0F, $0D, $0F, $0D, $0E, $0E, $0F
.BYTE $0D, $0F, $0F, $0B, $0D, $0E, $0E, $0F
.BYTE $0D, $0B, $0B, $0D, $0D, $0E, $0E, $0F
.BYTE $0D, $0D, $0D, $0D, $0D, $0E, $0E, $0F
.BYTE $00, $00, $00, $00, $00, $00, $00, $0F

ui_btn_sport:
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0D, $0D
.BYTE $0E, $0E, $0E, $0E, $0D, $0D, $0D, $0D
.BYTE $0E, $0E, $0E, $0D, $0D, $0D, $0D, $0F
.BYTE $0E, $0E, $0E, $0D, $0D, $0D, $0D, $0F
.BYTE $0E, $0E, $0D, $0D, $0D, $0D, $0D, $0D
.BYTE $0E, $0E, $0B, $0B, $0B, $0B, $05, $0D
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0B, $0D

.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0D, $0D, $0D, $0E, $0E, $0E, $0E, $0F
.BYTE $0D, $0D, $0D, $0D, $0E, $0E, $0E, $0F
.BYTE $0D, $0D, $0D, $0D, $0D, $0E, $0E, $0F
.BYTE $0F, $0D, $0D, $0D, $0D, $0D, $0E, $0F
.BYTE $0F, $0F, $0D, $0D, $0D, $0D, $0E, $0F
.BYTE $0D, $0D, $0D, $0D, $0D, $0D, $0D, $0F
.BYTE $0D, $0D, $0D, $0D, $0D, $0D, $0D, $0F

.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0F, $0F
.BYTE $0E, $0E, $0E, $0E, $0F, $0F, $0E, $0B
.BYTE $0E, $0F, $0F, $0F, $0F, $0E, $0B, $0F
.BYTE $0E, $0F, $0E, $0F, $0F, $0B, $0F, $0D
.BYTE $0E, $0E, $0F, $0E, $0F, $0F, $0D, $0D
.BYTE $0E, $0E, $0F, $0F, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $00, $00, $00, $00, $00, $00, $00, $00

.BYTE $0D, $0D, $0D, $0D, $0D, $0D, $0E, $0F
.BYTE $0F, $0D, $0D, $0D, $0D, $0D, $0E, $0F
.BYTE $0D, $0D, $0D, $0D, $0D, $0E, $0E, $0F
.BYTE $0D, $0D, $0D, $0D, $0E, $0E, $0E, $0F
.BYTE $0D, $0D, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $00, $00, $00, $00, $00, $00, $00, $0F

ui_btn_sea:
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0F, $0B
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0F, $0B
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0F, $0F, $0F, $0F
.BYTE $0E, $0E, $0E, $0E, $0F, $0F, $0F, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0B, $0B, $0F

.BYTE $0F, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0B, $0F, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0B, $0F, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0F, $0B, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0F, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0F, $0F, $0F, $0F, $0E, $0E, $0E, $0F
.BYTE $0F, $0F, $0F, $0F, $0E, $0E, $0E, $0F
.BYTE $0F, $0B, $0B, $0E, $0E, $0E, $0E, $0F

.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0F, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0F, $0F, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0F, $0F, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0F, $0F, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0B, $0F, $0F, $0F
.BYTE $00, $00, $00, $00, $00, $00, $00, $00

.BYTE $0F, $0B, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0F, $0B, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0F, $0B, $0E, $0E, $0E, $0F, $0E, $0F
.BYTE $0F, $0B, $0E, $0E, $0F, $0F, $0E, $0F
.BYTE $0F, $0B, $0E, $0F, $0F, $0B, $0E, $0F
.BYTE $0F, $0B, $0F, $0F, $0B, $0E, $0E, $0F
.BYTE $0F, $0F, $0F, $0B, $0E, $0E, $0E, $0F
.BYTE $00, $00, $00, $00, $00, $00, $0E, $0F

ui_btn_coalpp:
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0B, $0E, $0E, $0E, $0B, $0E
.BYTE $0E, $0E, $0B, $0B, $0E, $0E, $0B, $0B
.BYTE $0E, $0E, $0C, $0B, $0E, $0E, $0C, $0B
.BYTE $0E, $0E, $04, $04, $0E, $0E, $04, $04
.BYTE $0E, $0E, $0C, $0C, $0E, $0E, $0C, $0C
.BYTE $0E, $0E, $04, $04, $0E, $0E, $04, $04
.BYTE $0E, $0E, $04, $04, $0E, $0E, $04, $04

.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0C, $0F
.BYTE $0E, $0E, $0B, $0E, $0E, $0C, $0E, $0F
.BYTE $0E, $0E, $0B, $0B, $0C, $0C, $0C, $0F
.BYTE $0E, $0E, $0C, $0B, $0E, $0C, $0E, $0F
.BYTE $0E, $0E, $04, $04, $0C, $0E, $0E, $0F
.BYTE $0E, $0E, $0C, $0C, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $04, $04, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $04, $04, $0E, $0E, $0E, $0F

.BYTE $0E, $0C, $0C, $0C, $0C, $0C, $0C, $0C
.BYTE $0E, $0D, $0D, $0D, $0D, $0D, $0D, $0D
.BYTE $0E, $0D, $0D, $0D, $0D, $0D, $0D, $0D
.BYTE $0E, $0D, $0D, $0D, $0D, $0D, $0D, $0D
.BYTE $0E, $0D, $0D, $0D, $0D, $0D, $0D, $0D
.BYTE $0E, $05, $05, $05, $05, $05, $05, $05
.BYTE $02, $02, $02, $02, $02, $02, $02, $02
.BYTE $00, $00, $00, $00, $00, $00, $00, $00

.BYTE $0C, $0C, $0C, $0C, $0C, $0C, $0C, $0F
.BYTE $0D, $0D, $0D, $0D, $0D, $0D, $0D, $0F
.BYTE $0D, $0D, $0D, $0D, $0D, $0D, $0D, $0F
.BYTE $0D, $0A, $0D, $0D, $0A, $0D, $0D, $0F
.BYTE $0D, $0D, $0D, $0D, $0D, $0D, $0D, $0F
.BYTE $05, $05, $05, $05, $05, $05, $05, $0F
.BYTE $02, $02, $02, $02, $02, $02, $02, $0F
.BYTE $00, $00, $00, $00, $00, $00, $00, $0F

ui_btn_nuclearpp:
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0F, $0F, $0F, $0F, $0F, $05
.BYTE $0E, $0E, $0F, $0F, $0F, $0F, $0F, $05
.BYTE $0E, $0E, $0F, $0F, $0F, $0F, $0F, $05
.BYTE $0E, $0E, $0F, $0F, $0F, $0F, $0F, $05

.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0C, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0C, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0C, $0C, $0C, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0C, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0C, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F

.BYTE $0E, $0E, $0F, $0F, $0F, $0F, $0F, $05
.BYTE $0E, $0E, $0F, $0F, $0F, $0F, $0F, $05
.BYTE $0E, $0E, $0F, $0F, $0F, $0F, $0F, $05
.BYTE $0E, $0E, $0F, $0F, $0F, $0F, $0F, $05
.BYTE $0E, $0F, $0F, $0F, $0F, $0F, $0F, $0F
.BYTE $0E, $0F, $0F, $0F, $0F, $0F, $0F, $0F
.BYTE $02, $02, $02, $02, $02, $02, $02, $02
.BYTE $00, $00, $00, $00, $00, $00, $00, $00

.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $09, $09, $09, $09, $09, $09, $0B, $0F
.BYTE $09, $09, $09, $09, $09, $09, $0B, $0F
.BYTE $09, $09, $0A, $09, $0A, $09, $0B, $0F
.BYTE $05, $09, $09, $09, $09, $09, $0B, $0F
.BYTE $05, $05, $05, $05, $05, $05, $0B, $0F
.BYTE $02, $02, $02, $02, $02, $02, $02, $0F
.BYTE $00, $00, $00, $00, $00, $00, $00, $0F

ui_btn_air:
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0F, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0F, $0F
.BYTE $0E, $0E, $0E, $0C, $05, $0E, $0F, $0F
.BYTE $0E, $0E, $0F, $0F, $0F, $0F, $0F, $0F
.BYTE $0E, $0F, $0F, $0F, $0F, $0F, $0F, $0F

.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0C, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0C, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0C, $0C, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0F, $0C, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0C, $0C, $0E, $05, $0C, $0E, $0E, $0F
.BYTE $0F, $0C, $0F, $0F, $0F, $0F, $0E, $0F
.BYTE $0C, $0C, $0F, $0F, $0F, $0F, $0F, $0F

.BYTE $0E, $0E, $0B, $0B, $0B, $0B, $0F, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0F, $0F, $0F, $0F
.BYTE $0E, $0E, $0E, $0E, $0F, $0F, $0F, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0B, $0B, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $00, $00, $00, $00, $00, $00, $00, $00

.BYTE $0F, $0F, $0B, $0B, $0B, $0B, $0E, $0F
.BYTE $0C, $0B, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0C, $0B, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0F, $0F, $0F, $0F, $0E, $0E, $0E, $0F
.BYTE $0F, $0F, $0F, $0F, $0E, $0E, $0E, $0F
.BYTE $0F, $0B, $0B, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $00, $00, $00, $00, $00, $00, $00, $0F

ui_btn_special:
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0B, $0B
.BYTE $0E, $0E, $0E, $0E, $0E, $0B, $0B, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0B

.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0B, $0B, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0B, $0B, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0B, $0B, $0E, $0E, $0E, $0E, $0F
.BYTE $0B, $0B, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0B, $0E, $0E, $0E, $0E, $0E, $0E, $0F

.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0B
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0B
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0B
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0B
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0E
.BYTE $00, $00, $00, $00, $00, $00, $00, $00

.BYTE $0B, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0B, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0B, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0B, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $0E, $0E, $0E, $0E, $0E, $0E, $0E, $0F
.BYTE $00, $00, $00, $00, $00, $00, $00, $0F

ui_tiles_end:
        .cerror ui_tiles_end - ui_tiles_start != UI_TILE_ASSET_SIZE, "UI tile asset size mismatch"
