;=======================================================================================
; Static SimCity-style UI frame.
;=======================================================================================

LOAD_UI_TILE .macro index, label
        lda #\index
        ldx #<\label
        ldy #>\label
        jsr create_ncm_char
.endmacro

UI_TEXT_BG = $0E
UI_TEXT_FG = $08

UI_TEXT_ROW .macro p0, p1, p2, p3, p4
        .byte UI_TEXT_BG, \p0, \p1, \p2, \p3, \p4, UI_TEXT_BG, UI_TEXT_BG
.endmacro

ui_load:
        #LOAD_UI_TILE UI_TILE_PANEL, ui_data_panel
        #LOAD_UI_TILE UI_TILE_MENU, ui_data_menu
        #LOAD_UI_TILE UI_TILE_STATUS_LIGHT, ui_data_status_light
        #LOAD_UI_TILE UI_TILE_STATUS_DARK, ui_data_status_dark
        #LOAD_UI_TILE UI_TILE_FRAME, ui_data_frame
        #LOAD_UI_TILE UI_TILE_BOTTOM, ui_data_bottom
        #LOAD_UI_TILE UI_TILE_TOOL_ROAD, ui_data_tool_road
        #LOAD_UI_TILE UI_TILE_TOOL_RES, ui_data_tool_res
        #LOAD_UI_TILE UI_TILE_TOOL_COM, ui_data_tool_com
        #LOAD_UI_TILE UI_TILE_TOOL_IND, ui_data_tool_ind
        #LOAD_UI_TILE UI_TILE_TOOL_POWER, ui_data_tool_power
        #LOAD_UI_TILE UI_TILE_TOOL_WATER, ui_data_tool_water
        #LOAD_UI_TILE UI_TILE_HELP, ui_data_help
        #LOAD_UI_TILE UI_TILE_RCI_PANEL, ui_data_rci_panel
        #LOAD_UI_TILE UI_TEXT_A, ui_glyph_a
        #LOAD_UI_TILE UI_TEXT_B, ui_glyph_b
        #LOAD_UI_TILE UI_TEXT_C, ui_glyph_c
        #LOAD_UI_TILE UI_TEXT_D, ui_glyph_d
        #LOAD_UI_TILE UI_TEXT_E, ui_glyph_e
        #LOAD_UI_TILE UI_TEXT_F, ui_glyph_f
        #LOAD_UI_TILE UI_TEXT_G, ui_glyph_g
        #LOAD_UI_TILE UI_TEXT_H, ui_glyph_h
        #LOAD_UI_TILE UI_TEXT_I, ui_glyph_i
        #LOAD_UI_TILE UI_TEXT_J, ui_glyph_j
        #LOAD_UI_TILE UI_TEXT_K, ui_glyph_k
        #LOAD_UI_TILE UI_TEXT_L, ui_glyph_l
        #LOAD_UI_TILE UI_TEXT_M, ui_glyph_m
        #LOAD_UI_TILE UI_TEXT_N, ui_glyph_n
        #LOAD_UI_TILE UI_TEXT_O, ui_glyph_o
        #LOAD_UI_TILE UI_TEXT_P, ui_glyph_p
        #LOAD_UI_TILE UI_TEXT_Q, ui_glyph_q
        #LOAD_UI_TILE UI_TEXT_R, ui_glyph_r
        #LOAD_UI_TILE UI_TEXT_S, ui_glyph_s
        #LOAD_UI_TILE UI_TEXT_T, ui_glyph_t
        #LOAD_UI_TILE UI_TEXT_U, ui_glyph_u
        #LOAD_UI_TILE UI_TEXT_V, ui_glyph_v
        #LOAD_UI_TILE UI_TEXT_W, ui_glyph_w
        #LOAD_UI_TILE UI_TEXT_X, ui_glyph_x
        #LOAD_UI_TILE UI_TEXT_Y, ui_glyph_y
        #LOAD_UI_TILE UI_TEXT_Z, ui_glyph_z
        #LOAD_UI_TILE UI_TEXT_0, ui_glyph_0
        #LOAD_UI_TILE UI_TEXT_1, ui_glyph_1
        #LOAD_UI_TILE UI_TEXT_2, ui_glyph_2
        #LOAD_UI_TILE UI_TEXT_3, ui_glyph_3
        #LOAD_UI_TILE UI_TEXT_4, ui_glyph_4
        #LOAD_UI_TILE UI_TEXT_5, ui_glyph_5
        #LOAD_UI_TILE UI_TEXT_6, ui_glyph_6
        #LOAD_UI_TILE UI_TEXT_7, ui_glyph_7
        #LOAD_UI_TILE UI_TEXT_8, ui_glyph_8
        #LOAD_UI_TILE UI_TEXT_9, ui_glyph_9
        #LOAD_UI_TILE UI_TEXT_COMMA, ui_glyph_comma
        #LOAD_UI_TILE UI_TEXT_DOT, ui_glyph_dot
        #LOAD_UI_TILE UI_TEXT_DOLLAR, ui_glyph_dollar
        #LOAD_UI_TILE UI_TEXT_COLON, ui_glyph_colon
        rts

ui_data_panel:
        .fill 64, $0C

ui_data_menu:
        .fill 64, $0E

ui_data_status_light:
        .fill 64, $0C

ui_data_status_dark:
        .fill 64, $0C

ui_data_frame:
        .fill 64, $08

ui_data_bottom:
        .byte $08,$08,$08,$08,$08,$08,$08,$08
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $08,$08,$08,$08,$08,$08,$08,$08

ui_data_tool_road:
        .byte $07,$07,$07,$07,$07,$07,$07,$07
        .byte $07,$05,$05,$05,$05,$05,$05,$07
        .byte $07,$05,$06,$05,$05,$06,$05,$07
        .byte $07,$05,$05,$05,$05,$05,$05,$07
        .byte $07,$05,$05,$06,$05,$05,$06,$07
        .byte $07,$05,$05,$05,$05,$05,$05,$07
        .byte $07,$05,$05,$05,$05,$05,$05,$07
        .byte $07,$07,$07,$07,$07,$07,$07,$07

ui_data_tool_res:
        .byte $07,$07,$07,$07,$07,$07,$07,$07
        .byte $07,$00,$0D,$0D,$0D,$00,$00,$07
        .byte $07,$0D,$00,$00,$00,$0D,$00,$07
        .byte $07,$0D,$00,$00,$00,$0D,$00,$07
        .byte $07,$0D,$0D,$0D,$0D,$00,$00,$07
        .byte $07,$0D,$00,$0D,$00,$00,$00,$07
        .byte $07,$0D,$00,$00,$0D,$00,$00,$07
        .byte $07,$07,$07,$07,$07,$07,$07,$07

ui_data_tool_com:
        .byte $07,$07,$07,$07,$07,$07,$07,$07
        .byte $07,$00,$08,$08,$08,$08,$00,$07
        .byte $07,$08,$00,$00,$00,$00,$00,$07
        .byte $07,$08,$00,$00,$00,$00,$00,$07
        .byte $07,$08,$00,$00,$00,$00,$00,$07
        .byte $07,$08,$00,$00,$00,$00,$00,$07
        .byte $07,$00,$08,$08,$08,$08,$00,$07
        .byte $07,$07,$07,$07,$07,$07,$07,$07

ui_data_tool_ind:
        .byte $07,$07,$07,$07,$07,$07,$07,$07
        .byte $07,$00,$09,$09,$09,$00,$00,$07
        .byte $07,$00,$00,$09,$00,$00,$00,$07
        .byte $07,$00,$00,$09,$00,$00,$00,$07
        .byte $07,$00,$00,$09,$00,$00,$00,$07
        .byte $07,$00,$00,$09,$00,$00,$00,$07
        .byte $07,$00,$09,$09,$09,$00,$00,$07
        .byte $07,$07,$07,$07,$07,$07,$07,$07

ui_data_tool_power:
        .byte $07,$07,$07,$07,$07,$07,$07,$07
        .byte $07,$00,$00,$0A,$0A,$00,$00,$07
        .byte $07,$00,$0A,$0A,$00,$00,$00,$07
        .byte $07,$00,$00,$0A,$0A,$00,$00,$07
        .byte $07,$00,$00,$00,$0A,$0A,$00,$07
        .byte $07,$0B,$0B,$0A,$0A,$0B,$0B,$07
        .byte $07,$0B,$0B,$0B,$0B,$0B,$0B,$07
        .byte $07,$07,$07,$07,$07,$07,$07,$07

ui_data_tool_water:
        .byte $07,$07,$07,$07,$07,$07,$07,$07
        .byte $07,$01,$01,$01,$01,$01,$01,$07
        .byte $07,$01,$0E,$01,$01,$0E,$01,$07
        .byte $07,$01,$01,$01,$0E,$01,$01,$07
        .byte $07,$0E,$01,$01,$01,$01,$01,$07
        .byte $07,$01,$01,$0E,$01,$01,$0E,$07
        .byte $07,$01,$01,$01,$01,$01,$01,$07
        .byte $07,$07,$07,$07,$07,$07,$07,$07

ui_data_help:
        .byte $0A,$0A,$0A,$0A,$0A,$0A,$0A,$0A
        .byte $0A,$00,$00,$00,$00,$00,$00,$0A
        .byte $0A,$00,$0B,$0B,$0B,$00,$00,$0A
        .byte $0A,$00,$00,$00,$0B,$00,$00,$0A
        .byte $0A,$00,$00,$0B,$00,$00,$00,$0A
        .byte $0A,$00,$00,$0B,$00,$00,$00,$0A
        .byte $0A,$00,$00,$00,$00,$00,$00,$0A
        .byte $0A,$0A,$0A,$0A,$0A,$0A,$0A,$0A

ui_data_rci_panel:
        .fill 64, $0F

ui_glyph_a:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_b:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_c:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_d:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_e:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_f:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_g:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_h:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_i:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_j:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_k:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_l:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_m:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_n:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_o:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_p:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_q:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_r:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_s:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_t:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_u:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_v:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_w:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_x:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_y:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_z:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_0:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_1:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_2:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_3:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_4:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_5:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_6:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_7:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_8:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_9:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_comma:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_dot:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_dollar:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

ui_glyph_colon:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
