;=======================================================================================
; Static SimCity-style UI frame.
;=======================================================================================

UI_ASSET_OFF_PANEL          = 0
UI_ASSET_OFF_MENU           = UI_ASSET_OFF_PANEL + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_STATUS_LIGHT   = UI_ASSET_OFF_MENU + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_STATUS_DARK    = UI_ASSET_OFF_STATUS_LIGHT + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_FRAME          = UI_ASSET_OFF_STATUS_DARK + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_BOTTOM         = UI_ASSET_OFF_FRAME + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TOOL_ROAD      = UI_ASSET_OFF_BOTTOM + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_AFTER_ROAD     = UI_ASSET_OFF_TOOL_ROAD + UI_ROAD_ICON_SIZE
UI_ASSET_OFF_TOOL_RES       = UI_ASSET_OFF_AFTER_ROAD
UI_ASSET_OFF_TOOL_COM       = UI_ASSET_OFF_TOOL_RES + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TOOL_IND       = UI_ASSET_OFF_TOOL_COM + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TOOL_POWER     = UI_ASSET_OFF_TOOL_IND + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TOOL_WATER     = UI_ASSET_OFF_TOOL_POWER + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_HELP           = UI_ASSET_OFF_TOOL_WATER + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_RCI_PANEL      = UI_ASSET_OFF_HELP + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_A         = UI_ASSET_OFF_RCI_PANEL + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_B         = UI_ASSET_OFF_TEXT_A + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_C         = UI_ASSET_OFF_TEXT_B + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_D         = UI_ASSET_OFF_TEXT_C + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_E         = UI_ASSET_OFF_TEXT_D + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_F         = UI_ASSET_OFF_TEXT_E + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_G         = UI_ASSET_OFF_TEXT_F + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_H         = UI_ASSET_OFF_TEXT_G + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_I         = UI_ASSET_OFF_TEXT_H + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_J         = UI_ASSET_OFF_TEXT_I + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_K         = UI_ASSET_OFF_TEXT_J + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_L         = UI_ASSET_OFF_TEXT_K + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_M         = UI_ASSET_OFF_TEXT_L + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_N         = UI_ASSET_OFF_TEXT_M + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_O         = UI_ASSET_OFF_TEXT_N + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_P         = UI_ASSET_OFF_TEXT_O + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_Q         = UI_ASSET_OFF_TEXT_P + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_R         = UI_ASSET_OFF_TEXT_Q + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_S         = UI_ASSET_OFF_TEXT_R + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_T         = UI_ASSET_OFF_TEXT_S + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_U         = UI_ASSET_OFF_TEXT_T + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_V         = UI_ASSET_OFF_TEXT_U + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_W         = UI_ASSET_OFF_TEXT_V + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_X         = UI_ASSET_OFF_TEXT_W + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_Y         = UI_ASSET_OFF_TEXT_X + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_Z         = UI_ASSET_OFF_TEXT_Y + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_0         = UI_ASSET_OFF_TEXT_Z + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_1         = UI_ASSET_OFF_TEXT_0 + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_2         = UI_ASSET_OFF_TEXT_1 + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_3         = UI_ASSET_OFF_TEXT_2 + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_4         = UI_ASSET_OFF_TEXT_3 + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_5         = UI_ASSET_OFF_TEXT_4 + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_6         = UI_ASSET_OFF_TEXT_5 + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_7         = UI_ASSET_OFF_TEXT_6 + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_8         = UI_ASSET_OFF_TEXT_7 + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_9         = UI_ASSET_OFF_TEXT_8 + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_COMMA     = UI_ASSET_OFF_TEXT_9 + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_DOT       = UI_ASSET_OFF_TEXT_COMMA + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_DOLLAR    = UI_ASSET_OFF_TEXT_DOT + UI_TILE_CHAR_SIZE
UI_ASSET_OFF_TEXT_COLON     = UI_ASSET_OFF_TEXT_DOLLAR + UI_TILE_CHAR_SIZE

UI_TILE_DMA .macro index, size, offset
        lda #$00
        sta $D707
        .byte $80, ATTIC_UI_TILE_MB
        .byte $81, $00
        .byte $00
        .byte $00
        .word \size
        .word ATTIC_UI_TILE_ADDR + UI_TILE_INDEX_SIZE + \offset
        .byte ATTIC_UI_TILE_BANK
        .word \index * UI_TILE_CHAR_SIZE
        .byte `CHAR_DATA
        .byte $00
        .word $0000
.endmacro

UI_TILE_INDEX_ENTRY .macro index, size, width_cells, height_cells, offset
        .word \index
        .word \size
        .byte \width_cells, \height_cells
        .word \offset
.endmacro

UI_TEXT_BG = $0E
UI_TEXT_FG = $08
UI_ROAD_BG = $0A
UI_ROAD_BLUE = $08
UI_ROAD_WHITE = $0F
UI_ROAD_SHADOW = $00

UI_TEXT_ROW .macro p0, p1, p2, p3, p4
        .byte UI_TEXT_BG, \p0, \p1, \p2, \p3, \p4, UI_TEXT_BG, UI_TEXT_BG
.endmacro

UI_ROAD_ICON_CELL .macro cell_x, cell_y
.for py = 0, py < 8, py = py + 1
.for px = 0, px < 8, px = px + 1
.if ((\cell_y * 8 + py) >= 7) && ((\cell_y * 8 + py) <= 8) && ((((\cell_x * 8 + px) >= 2) && ((\cell_x * 8 + px) <= 4)) || (((\cell_x * 8 + px) >= 7) && ((\cell_x * 8 + px) <= 9)) || (((\cell_x * 8 + px) >= 12) && ((\cell_x * 8 + px) <= 14)))
        .byte UI_ROAD_WHITE
.elsif ((\cell_x * 8 + px) >= 1) && ((\cell_x * 8 + px) <= 14) && ((\cell_y * 8 + py) >= 5) && ((\cell_y * 8 + py) <= 10)
        .byte UI_ROAD_BLUE
.elsif ((((\cell_x * 8 + px) >= 2) && ((\cell_x * 8 + px) <= 15) && ((\cell_y * 8 + py) >= 11) && ((\cell_y * 8 + py) <= 12)) || (((\cell_x * 8 + px) >= 14) && ((\cell_y * 8 + py) >= 6) && ((\cell_y * 8 + py) <= 12)))
        .byte UI_ROAD_SHADOW
.else
        .byte UI_ROAD_BG
.endif
.next
.next
.endmacro

.if UI_TILE_ASSET_BUILD
UI_TILE_RECORD .macro index
.endmacro

ui_tile_index:
        #UI_TILE_INDEX_ENTRY UI_TILE_PANEL, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_PANEL
        #UI_TILE_INDEX_ENTRY UI_TILE_MENU, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_MENU
        #UI_TILE_INDEX_ENTRY UI_TILE_STATUS_LIGHT, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_STATUS_LIGHT
        #UI_TILE_INDEX_ENTRY UI_TILE_STATUS_DARK, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_STATUS_DARK
        #UI_TILE_INDEX_ENTRY UI_TILE_FRAME, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_FRAME
        #UI_TILE_INDEX_ENTRY UI_TILE_BOTTOM, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_BOTTOM
        #UI_TILE_INDEX_ENTRY UI_TILE_TOOL_ROAD, UI_ROAD_ICON_SIZE, UI_ROAD_ICON_CELLS_X, UI_ROAD_ICON_CELLS_Y, UI_ASSET_OFF_TOOL_ROAD
        #UI_TILE_INDEX_ENTRY UI_TILE_TOOL_RES, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TOOL_RES
        #UI_TILE_INDEX_ENTRY UI_TILE_TOOL_COM, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TOOL_COM
        #UI_TILE_INDEX_ENTRY UI_TILE_TOOL_IND, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TOOL_IND
        #UI_TILE_INDEX_ENTRY UI_TILE_TOOL_POWER, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TOOL_POWER
        #UI_TILE_INDEX_ENTRY UI_TILE_TOOL_WATER, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TOOL_WATER
        #UI_TILE_INDEX_ENTRY UI_TILE_HELP, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_HELP
        #UI_TILE_INDEX_ENTRY UI_TILE_RCI_PANEL, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_RCI_PANEL
        #UI_TILE_INDEX_ENTRY UI_TEXT_A, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_A
        #UI_TILE_INDEX_ENTRY UI_TEXT_B, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_B
        #UI_TILE_INDEX_ENTRY UI_TEXT_C, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_C
        #UI_TILE_INDEX_ENTRY UI_TEXT_D, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_D
        #UI_TILE_INDEX_ENTRY UI_TEXT_E, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_E
        #UI_TILE_INDEX_ENTRY UI_TEXT_F, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_F
        #UI_TILE_INDEX_ENTRY UI_TEXT_G, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_G
        #UI_TILE_INDEX_ENTRY UI_TEXT_H, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_H
        #UI_TILE_INDEX_ENTRY UI_TEXT_I, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_I
        #UI_TILE_INDEX_ENTRY UI_TEXT_J, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_J
        #UI_TILE_INDEX_ENTRY UI_TEXT_K, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_K
        #UI_TILE_INDEX_ENTRY UI_TEXT_L, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_L
        #UI_TILE_INDEX_ENTRY UI_TEXT_M, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_M
        #UI_TILE_INDEX_ENTRY UI_TEXT_N, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_N
        #UI_TILE_INDEX_ENTRY UI_TEXT_O, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_O
        #UI_TILE_INDEX_ENTRY UI_TEXT_P, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_P
        #UI_TILE_INDEX_ENTRY UI_TEXT_Q, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_Q
        #UI_TILE_INDEX_ENTRY UI_TEXT_R, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_R
        #UI_TILE_INDEX_ENTRY UI_TEXT_S, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_S
        #UI_TILE_INDEX_ENTRY UI_TEXT_T, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_T
        #UI_TILE_INDEX_ENTRY UI_TEXT_U, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_U
        #UI_TILE_INDEX_ENTRY UI_TEXT_V, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_V
        #UI_TILE_INDEX_ENTRY UI_TEXT_W, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_W
        #UI_TILE_INDEX_ENTRY UI_TEXT_X, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_X
        #UI_TILE_INDEX_ENTRY UI_TEXT_Y, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_Y
        #UI_TILE_INDEX_ENTRY UI_TEXT_Z, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_Z
        #UI_TILE_INDEX_ENTRY UI_TEXT_0, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_0
        #UI_TILE_INDEX_ENTRY UI_TEXT_1, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_1
        #UI_TILE_INDEX_ENTRY UI_TEXT_2, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_2
        #UI_TILE_INDEX_ENTRY UI_TEXT_3, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_3
        #UI_TILE_INDEX_ENTRY UI_TEXT_4, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_4
        #UI_TILE_INDEX_ENTRY UI_TEXT_5, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_5
        #UI_TILE_INDEX_ENTRY UI_TEXT_6, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_6
        #UI_TILE_INDEX_ENTRY UI_TEXT_7, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_7
        #UI_TILE_INDEX_ENTRY UI_TEXT_8, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_8
        #UI_TILE_INDEX_ENTRY UI_TEXT_9, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_9
        #UI_TILE_INDEX_ENTRY UI_TEXT_COMMA, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_COMMA
        #UI_TILE_INDEX_ENTRY UI_TEXT_DOT, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_DOT
        #UI_TILE_INDEX_ENTRY UI_TEXT_DOLLAR, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_DOLLAR
        #UI_TILE_INDEX_ENTRY UI_TEXT_COLON, UI_TILE_CHAR_SIZE, 1, 1, UI_ASSET_OFF_TEXT_COLON
.else
ui_load:
        #UI_TILE_DMA UI_TILE_PANEL, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_PANEL
        #UI_TILE_DMA UI_TILE_MENU, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_MENU
        #UI_TILE_DMA UI_TILE_STATUS_LIGHT, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_STATUS_LIGHT
        #UI_TILE_DMA UI_TILE_STATUS_DARK, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_STATUS_DARK
        #UI_TILE_DMA UI_TILE_FRAME, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_FRAME
        #UI_TILE_DMA UI_TILE_BOTTOM, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_BOTTOM
        #UI_TILE_DMA UI_TILE_TOOL_ROAD, UI_ROAD_ICON_SIZE, UI_ASSET_OFF_TOOL_ROAD
        #UI_TILE_DMA UI_TILE_TOOL_RES, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TOOL_RES
        #UI_TILE_DMA UI_TILE_TOOL_COM, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TOOL_COM
        #UI_TILE_DMA UI_TILE_TOOL_IND, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TOOL_IND
        #UI_TILE_DMA UI_TILE_TOOL_POWER, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TOOL_POWER
        #UI_TILE_DMA UI_TILE_TOOL_WATER, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TOOL_WATER
        #UI_TILE_DMA UI_TILE_HELP, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_HELP
        #UI_TILE_DMA UI_TILE_RCI_PANEL, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_RCI_PANEL
        #UI_TILE_DMA UI_TEXT_A, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_A
        #UI_TILE_DMA UI_TEXT_B, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_B
        #UI_TILE_DMA UI_TEXT_C, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_C
        #UI_TILE_DMA UI_TEXT_D, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_D
        #UI_TILE_DMA UI_TEXT_E, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_E
        #UI_TILE_DMA UI_TEXT_F, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_F
        #UI_TILE_DMA UI_TEXT_G, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_G
        #UI_TILE_DMA UI_TEXT_H, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_H
        #UI_TILE_DMA UI_TEXT_I, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_I
        #UI_TILE_DMA UI_TEXT_J, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_J
        #UI_TILE_DMA UI_TEXT_K, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_K
        #UI_TILE_DMA UI_TEXT_L, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_L
        #UI_TILE_DMA UI_TEXT_M, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_M
        #UI_TILE_DMA UI_TEXT_N, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_N
        #UI_TILE_DMA UI_TEXT_O, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_O
        #UI_TILE_DMA UI_TEXT_P, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_P
        #UI_TILE_DMA UI_TEXT_Q, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_Q
        #UI_TILE_DMA UI_TEXT_R, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_R
        #UI_TILE_DMA UI_TEXT_S, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_S
        #UI_TILE_DMA UI_TEXT_T, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_T
        #UI_TILE_DMA UI_TEXT_U, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_U
        #UI_TILE_DMA UI_TEXT_V, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_V
        #UI_TILE_DMA UI_TEXT_W, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_W
        #UI_TILE_DMA UI_TEXT_X, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_X
        #UI_TILE_DMA UI_TEXT_Y, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_Y
        #UI_TILE_DMA UI_TEXT_Z, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_Z
        #UI_TILE_DMA UI_TEXT_0, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_0
        #UI_TILE_DMA UI_TEXT_1, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_1
        #UI_TILE_DMA UI_TEXT_2, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_2
        #UI_TILE_DMA UI_TEXT_3, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_3
        #UI_TILE_DMA UI_TEXT_4, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_4
        #UI_TILE_DMA UI_TEXT_5, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_5
        #UI_TILE_DMA UI_TEXT_6, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_6
        #UI_TILE_DMA UI_TEXT_7, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_7
        #UI_TILE_DMA UI_TEXT_8, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_8
        #UI_TILE_DMA UI_TEXT_9, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_9
        #UI_TILE_DMA UI_TEXT_COMMA, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_COMMA
        #UI_TILE_DMA UI_TEXT_DOT, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_DOT
        #UI_TILE_DMA UI_TEXT_DOLLAR, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_DOLLAR
        #UI_TILE_DMA UI_TEXT_COLON, UI_TILE_CHAR_SIZE, UI_ASSET_OFF_TEXT_COLON
        rts
.endif

.if UI_TILE_ASSET_BUILD

#UI_TILE_RECORD UI_TILE_PANEL
ui_data_panel:
        .fill 64, $0C

#UI_TILE_RECORD UI_TILE_MENU
ui_data_menu:
        .fill 64, $0E

#UI_TILE_RECORD UI_TILE_STATUS_LIGHT
ui_data_status_light:
        .fill 64, $0C

#UI_TILE_RECORD UI_TILE_STATUS_DARK
ui_data_status_dark:
        .fill 64, $0C

#UI_TILE_RECORD UI_TILE_FRAME
ui_data_frame:
        .fill 64, $08

#UI_TILE_RECORD UI_TILE_BOTTOM
ui_data_bottom:
        .byte $08,$08,$08,$08,$08,$08,$08,$08
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $0F,$0F,$0F,$0F,$0F,$0F,$0F,$0F
        .byte $08,$08,$08,$08,$08,$08,$08,$08

#UI_TILE_RECORD UI_TILE_TOOL_ROAD
ui_data_tool_road:
.for road_cy = 0, road_cy < UI_ROAD_ICON_CELLS_Y, road_cy = road_cy + 1
.for road_cx = 0, road_cx < UI_ROAD_ICON_CELLS_X, road_cx = road_cx + 1
        #UI_ROAD_ICON_CELL road_cx, road_cy
.next
.next

#UI_TILE_RECORD UI_TILE_TOOL_RES
ui_data_tool_res:
        .byte $07,$07,$07,$07,$07,$07,$07,$07
        .byte $07,$00,$0D,$0D,$0D,$00,$00,$07
        .byte $07,$0D,$00,$00,$00,$0D,$00,$07
        .byte $07,$0D,$00,$00,$00,$0D,$00,$07
        .byte $07,$0D,$0D,$0D,$0D,$00,$00,$07
        .byte $07,$0D,$00,$0D,$00,$00,$00,$07
        .byte $07,$0D,$00,$00,$0D,$00,$00,$07
        .byte $07,$07,$07,$07,$07,$07,$07,$07

#UI_TILE_RECORD UI_TILE_TOOL_COM
ui_data_tool_com:
        .byte $07,$07,$07,$07,$07,$07,$07,$07
        .byte $07,$00,$08,$08,$08,$08,$00,$07
        .byte $07,$08,$00,$00,$00,$00,$00,$07
        .byte $07,$08,$00,$00,$00,$00,$00,$07
        .byte $07,$08,$00,$00,$00,$00,$00,$07
        .byte $07,$08,$00,$00,$00,$00,$00,$07
        .byte $07,$00,$08,$08,$08,$08,$00,$07
        .byte $07,$07,$07,$07,$07,$07,$07,$07

#UI_TILE_RECORD UI_TILE_TOOL_IND
ui_data_tool_ind:
        .byte $07,$07,$07,$07,$07,$07,$07,$07
        .byte $07,$00,$09,$09,$09,$00,$00,$07
        .byte $07,$00,$00,$09,$00,$00,$00,$07
        .byte $07,$00,$00,$09,$00,$00,$00,$07
        .byte $07,$00,$00,$09,$00,$00,$00,$07
        .byte $07,$00,$00,$09,$00,$00,$00,$07
        .byte $07,$00,$09,$09,$09,$00,$00,$07
        .byte $07,$07,$07,$07,$07,$07,$07,$07

#UI_TILE_RECORD UI_TILE_TOOL_POWER
ui_data_tool_power:
        .byte $07,$07,$07,$07,$07,$07,$07,$07
        .byte $07,$00,$00,$0A,$0A,$00,$00,$07
        .byte $07,$00,$0A,$0A,$00,$00,$00,$07
        .byte $07,$00,$00,$0A,$0A,$00,$00,$07
        .byte $07,$00,$00,$00,$0A,$0A,$00,$07
        .byte $07,$0B,$0B,$0A,$0A,$0B,$0B,$07
        .byte $07,$0B,$0B,$0B,$0B,$0B,$0B,$07
        .byte $07,$07,$07,$07,$07,$07,$07,$07

#UI_TILE_RECORD UI_TILE_TOOL_WATER
ui_data_tool_water:
        .byte $07,$07,$07,$07,$07,$07,$07,$07
        .byte $07,$01,$01,$01,$01,$01,$01,$07
        .byte $07,$01,$0E,$01,$01,$0E,$01,$07
        .byte $07,$01,$01,$01,$0E,$01,$01,$07
        .byte $07,$0E,$01,$01,$01,$01,$01,$07
        .byte $07,$01,$01,$0E,$01,$01,$0E,$07
        .byte $07,$01,$01,$01,$01,$01,$01,$07
        .byte $07,$07,$07,$07,$07,$07,$07,$07

#UI_TILE_RECORD UI_TILE_HELP
ui_data_help:
        .byte $0A,$0A,$0A,$0A,$0A,$0A,$0A,$0A
        .byte $0A,$00,$00,$00,$00,$00,$00,$0A
        .byte $0A,$00,$0B,$0B,$0B,$00,$00,$0A
        .byte $0A,$00,$00,$00,$0B,$00,$00,$0A
        .byte $0A,$00,$00,$0B,$00,$00,$00,$0A
        .byte $0A,$00,$00,$0B,$00,$00,$00,$0A
        .byte $0A,$00,$00,$00,$00,$00,$00,$0A
        .byte $0A,$0A,$0A,$0A,$0A,$0A,$0A,$0A

#UI_TILE_RECORD UI_TILE_RCI_PANEL
ui_data_rci_panel:
        .fill 64, $0F

#UI_TILE_RECORD UI_TEXT_A
ui_glyph_a:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_B
ui_glyph_b:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_C
ui_glyph_c:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_D
ui_glyph_d:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_E
ui_glyph_e:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_F
ui_glyph_f:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_G
ui_glyph_g:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_H
ui_glyph_h:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_I
ui_glyph_i:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_J
ui_glyph_j:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_K
ui_glyph_k:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_L
ui_glyph_l:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_M
ui_glyph_m:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_N
ui_glyph_n:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_O
ui_glyph_o:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_P
ui_glyph_p:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_Q
ui_glyph_q:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_R
ui_glyph_r:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_S
ui_glyph_s:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_T
ui_glyph_t:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_U
ui_glyph_u:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_V
ui_glyph_v:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_W
ui_glyph_w:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_X
ui_glyph_x:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_Y
ui_glyph_y:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_Z
ui_glyph_z:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_0
ui_glyph_0:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_1
ui_glyph_1:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_2
ui_glyph_2:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_3
ui_glyph_3:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_4
ui_glyph_4:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_5
ui_glyph_5:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_6
ui_glyph_6:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_7
ui_glyph_7:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_8
ui_glyph_8:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_9
ui_glyph_9:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_COMMA
ui_glyph_comma:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_DOT
ui_glyph_dot:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_DOLLAR
ui_glyph_dollar:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_FG
        #UI_TEXT_ROW UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_FG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

#UI_TILE_RECORD UI_TEXT_COLON
ui_glyph_colon:
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_FG, UI_TEXT_BG, UI_TEXT_BG
        #UI_TEXT_ROW UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG, UI_TEXT_BG

.endif
